/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUSChiTietHoaDon;
import BUS.BUSHoaDon;
import BUS.BUSKhachHang;
import BUS.BUSKhoSach;
import BUS.BUSTaiKhoan;
import DAO.DAOChiTietHoaDon;
import DAO.DAOKhachHang;
import DAO.DAOKhoSach;
import DAO.DAOHoaDon;
import DTO.DTOChiTietHoaDon;
import DTO.DTOKhachHang;
import DTO.DTOKhoSach;
import DTO.DTOHoaDon;
import DTO.DTOTaiKhoan;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BanHang_View extends javax.swing.JFrame {
    DefaultTableModel model;
    ArrayList<DTOKhoSach> list;
    ArrayList<DTOKhachHang> list_kh;
    ArrayList<DTOHoaDon> list_hd;
    ArrayList<DTOTaiKhoan> list_tk = new BUSTaiKhoan().getAllTaiKhoan();
    static String MaNV, TenNV;
    int TongTien_int = 0;
    int SoTienTra = 0;
     //phuong thuc de in 1 so ra thanh tien te trong java
    Locale localVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localVN);
    /**
     * Creates new form NhapHang
     */
    public BanHang_View(String MaNV, String TenNV) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);//phat toan man hinh
        String[] header = {"Ma Sach", "Ten Sach", "Gia Sach", "So Luong", "Thanh tien"};
        model = new DefaultTableModel(header,0);
        tblBanSach.setModel(model);
        
        //Truy van ra arraylist da bao gom trong ham Reset()
//        list = new DAOKhoSach().getListSach();
//        list_kh = new DAOKhachHang().getListKH();
//        list_hd = new DAOHoaDon().getListHoaDon();
        
        //Set cac chuc nang mac dinh cho he thông
        jpNhapThongTinKhach.setVisible(false);
        txtSDT_NHAP.setEditable(false);
        tblHoaDon.setEnabled(false);
        
        
        
        this.MaNV = MaNV;
        this.TenNV = TenNV;
        
        lblHello.setText("Hi " + this.TenNV);
        
        
        for(DTOTaiKhoan s : list_tk){
            if(s.getMaNhanVien().equals(MaNV)){
                if(s.getChucVu().equals("Sale")){
                    System.out.println(s.getChucVu());
                    lbNhaCungCap5.setVisible(false);
                    lbNhanVien4.setVisible(false);
                    lbNhapSach4.setVisible(false);
                    lbKH11.setVisible(false);
                    lbBookStore4.setVisible(false);
                    lblBill4.setVisible(false);
                    lbPhieu10.setVisible(false);
                }
            }
        }
        
        Reset();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BackGround = new javax.swing.JPanel();
        BangChon = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        TieuDe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanSach = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTongTien_Nhap = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jpThongTinKhach = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTichDiem = new javax.swing.JLabel();
        lblSDTKH = new javax.swing.JLabel();
        lblDiaChiKH = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        btnTiepTuc = new javax.swing.JButton();
        jpNhapThongTinKhach = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAddKH = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT_NHAP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        lblNgayLap = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblMaKH_HD = new javax.swing.JLabel();
        lblTenKH_HD = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblMaGiamGia = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblSoTienTra = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        ThanhMenu4 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        lbNhanVien4 = new javax.swing.JLabel();
        lbBanSach4 = new javax.swing.JLabel();
        lbNhaCungCap5 = new javax.swing.JLabel();
        lbPhieu10 = new javax.swing.JLabel();
        lbNhapSach4 = new javax.swing.JLabel();
        lbKH11 = new javax.swing.JLabel();
        lblBill4 = new javax.swing.JLabel();
        lbBookStore4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));

        BangChon.setBackground(new java.awt.Color(0, 153, 153));

        txtFind.setText("nhap ma sach");
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-to-basket.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 204, 153));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_giohang.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangChonLayout = new javax.swing.GroupLayout(BangChon);
        BangChon.setLayout(BangChonLayout);
        BangChonLayout.setHorizontalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BangChonLayout.setVerticalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFind)
            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TieuDe.setBackground(new java.awt.Color(153, 102, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Hệ thống quản lý cửa hàng sách");

        javax.swing.GroupLayout TieuDeLayout = new javax.swing.GroupLayout(TieuDe);
        TieuDe.setLayout(TieuDeLayout);
        TieuDeLayout.setHorizontalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDeLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        TieuDeLayout.setVerticalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setLayout(new java.awt.BorderLayout());

        tblBanSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá tiền", "Số lượng", "Thành tiền"
            }
        ));
        tblBanSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanSach);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tong Tien:");

        lblTongTien_Nhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien_Nhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien_Nhap.setText("0");

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblTongTien_Nhap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Thong tin san pham", jPanel4);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nhập số điện thoại: ");

        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tên khách hàng: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mã khách hàng:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Địa chỉ:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Số điện thoại:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Số điểm đã tích:");

        lblTichDiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblSDTKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblDiaChiKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblTenKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnTiepTuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTiepTuc.setText("Tiếp tục");
        btnTiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpThongTinKhachLayout = new javax.swing.GroupLayout(jpThongTinKhach);
        jpThongTinKhach.setLayout(jpThongTinKhachLayout);
        jpThongTinKhachLayout.setHorizontalGroup(
            jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinKhachLayout.createSequentialGroup()
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinKhachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(161, 161, 161)
                        .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenKH)
                            .addComponent(lblDiaChiKH)
                            .addComponent(lblSDTKH)
                            .addComponent(lblTichDiem)))
                    .addGroup(jpThongTinKhachLayout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(btnTiepTuc)))
                .addGap(0, 471, Short.MAX_VALUE))
        );
        jpThongTinKhachLayout.setVerticalGroup(
            jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinKhachLayout.createSequentialGroup()
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTenKH))
                .addGap(18, 18, 18)
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaKH)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDiaChiKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblSDTKH))
                .addGap(18, 18, 18)
                .addGroup(jpThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTichDiem)
                    .addComponent(jLabel12))
                .addGap(5, 5, 5)
                .addComponent(btnTiepTuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tên khách hàng: ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Địa chỉ:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Số điện thoại:");

        btnAddKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddKH.setText("Thêm khách hàng");
        btnAddKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNhapThongTinKhachLayout = new javax.swing.GroupLayout(jpNhapThongTinKhach);
        jpNhapThongTinKhach.setLayout(jpNhapThongTinKhachLayout);
        jpNhapThongTinKhachLayout.setHorizontalGroup(
            jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNhapThongTinKhachLayout.createSequentialGroup()
                .addGroup(jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(165, 165, 165)
                .addGroup(jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(txtDiaChi)
                    .addComponent(txtSDT_NHAP))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpNhapThongTinKhachLayout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(btnAddKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpNhapThongTinKhachLayout.setVerticalGroup(
            jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNhapThongTinKhachLayout.createSequentialGroup()
                .addGroup(jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpNhapThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSDT_NHAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(146, 146, 146)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpNhapThongTinKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jpThongTinKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan))
                .addGap(18, 18, 18)
                .addComponent(jpNhapThongTinKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpThongTinKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(168, 168, 168))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thong tin khach hang", jPanel5);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Mã hóa đơn:");

        lblMaPhieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhieu.setText("123456");

        lblNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgayLap.setText("5/3/2023");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Ngày lập:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Mã khách hàng:");

        lblMaKH_HD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaKH_HD.setText("4569123248567");

        lblTenKH_HD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenKH_HD.setText("Nguyen Van A");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Tên khách hàng:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Mã nhân viên: ");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNV.setText("3121410298");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Tên nhân viên:");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("Lê Văn B");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaNV)
                                .addComponent(lblTenKH_HD)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel18))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(lblMaKH_HD)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(lblMaPhieu))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(lblNgayLap))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(lblMaKH_HD))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(lblTenKH_HD))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(lblMaNV))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Chi Tiết Hóa Đơn");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Cửa hàng: ACĐSDSDSD");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma Sach", "Ten Sach", "Gia Sach", "So Luong", "Thanh Tien"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDon);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tổng giá trị hóa đơn:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien.setText("189.232.232");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Thông tin giảm giá:");

        lblMaGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaGiamGia.setText("JQK");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Số tiền phải trả: ");

        lblSoTienTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoTienTra.setText("150.263.959");

        btnThanhToan.setText("Thanh Toan");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMaGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel27))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSoTienTra)
                                        .addComponent(lblTongTien))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(492, 492, 492))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblTongTien))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(lblMaGiamGia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(lblSoTienTra))
                        .addGap(28, 28, 28)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );

        jTabbedPane1.addTab("Chi TietHoa Don", jPanel2);

        ThanhMenu4.setBackground(new java.awt.Color(0, 153, 153));

        lblHello.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon minion.png"))); // NOI18N
        lblHello.setText("Hi You");
        lblHello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHello.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbNhanVien4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhanVien4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanVien4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Employee.png"))); // NOI18N
        lbNhanVien4.setText("  Nhân viên");
        lbNhanVien4.setToolTipText("");
        lbNhanVien4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhanVien4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanVien4MouseClicked(evt);
            }
        });

        lbBanSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbBanSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBanSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookSales.png"))); // NOI18N
        lbBanSach4.setText("  Bán sách");
        lbBanSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBanSach4.setOpaque(true);
        lbBanSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanSach4MouseClicked(evt);
            }
        });

        lbNhaCungCap5.setBackground(new java.awt.Color(0, 204, 204));
        lbNhaCungCap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhaCungCap5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhaCungCap5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Suppliers.png"))); // NOI18N
        lbNhaCungCap5.setText("  Nhà xuất bản");
        lbNhaCungCap5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhaCungCap5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhaCungCap5MouseClicked(evt);
            }
        });

        lbPhieu10.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coupons.png"))); // NOI18N
        lbPhieu10.setText("  Phiếu nhập");
        lbPhieu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu10MouseClicked(evt);
            }
        });

        lbNhapSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhapSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhapSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhapSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImportBook.png"))); // NOI18N
        lbNhapSach4.setText("  Nhập sách");
        lbNhapSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhapSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhapSach4MouseClicked(evt);
            }
        });

        lbKH11.setBackground(new java.awt.Color(0, 204, 204));
        lbKH11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbKH11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbKH11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        lbKH11.setText("  Khách hàng");
        lbKH11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbKH11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbKH11MouseClicked(evt);
            }
        });

        lblBill4.setBackground(new java.awt.Color(0, 204, 204));
        lblBill4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBill4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill.png"))); // NOI18N
        lblBill4.setText("  Hóa đơn");
        lblBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBill4MouseClicked(evt);
            }
        });

        lbBookStore4.setBackground(new java.awt.Color(0, 204, 204));
        lbBookStore4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBookStore4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBookStore4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookStore.png"))); // NOI18N
        lbBookStore4.setText(" Cửa hàng sách");
        lbBookStore4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBookStore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBookStore4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThanhMenu4Layout = new javax.swing.GroupLayout(ThanhMenu4);
        ThanhMenu4.setLayout(ThanhMenu4Layout);
        ThanhMenu4Layout.setHorizontalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBanSach4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhanVien4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapSach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhaCungCap5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbKH11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBill4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBookStore4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThanhMenu4Layout.setVerticalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhanVien4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhapSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhaCungCap5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbKH11)
                .addGap(18, 18, 18)
                .addComponent(lbPhieu10)
                .addGap(18, 18, 18)
                .addComponent(lblBill4)
                .addGap(18, 18, 18)
                .addComponent(lbBookStore4)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(ThanhMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BangChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addComponent(TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ThanhMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String SDT = txtSDT.getText();
        if(SDT.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap so dien thoai cua khach hang");
            return;
        }
        
        if(SDT.length() != 10){
            JOptionPane.showMessageDialog(rootPane, "So dien thoai phai co 10 chu so");
            return;
        }
        
        for(DTOKhachHang s : list_kh){
            if(s.getMaKH().equals(SDT)){
                lblMaKH.setText(s.getMaKH());
                lblTenKH.setText(s.getTenKH());
                lblDiaChiKH.setText(s.getDiaChi());
                lblSDTKH.setText(s.getSDT());
                lblTichDiem.setText(Integer.toString(s.getTichDiem()));
                jpNhapThongTinKhach.setVisible(false);
                jpThongTinKhach.setVisible(true);
                return;
            }
        }
        
        jpNhapThongTinKhach.setVisible(true);
        jpThongTinKhach.setVisible(false);
        txtSDT_NHAP.setText(SDT);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        if(tblBanSach.getRowCount() == 0){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap thong tin mua hang");
            return;
        }
        BangChon.setVisible(false);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    private boolean KiemTraSach(String masach){
        for (int i = 0; i < tblBanSach.getRowCount();i++){
            if (tblBanSach.getValueAt(i, 0).equals(masach)){
                return false;
            }
        }
        return true;
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String masach = txtFind.getText();
        int sl_int=0;
       
        if(masach.equals("nhap ma hang")){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap ma hang");
            txtFind.requestFocus();
            return;
        }
        if (KiemTraSach(masach) == true){
                for (DTOKhoSach s : list){
                if(s.getMaSach().equals(masach)){
                    do{

                        String sl = JOptionPane.showInputDialog("Nhap so luong khach mua");
                        //Kiem tra nguoi dung co muon thoat khoi muc nhap so luong khong
                        if(sl == null){
                            txtFind.setText("nhap ma sach");
                            txtFind.requestFocus();
                            return;
                        }



                        //Cac loi sai ve so luong de de nguoi dung nhap lai so luong
                        //Kiem tra xem nguoi dung co nhap so luong la ki tu hay khong
                        try{
                            sl_int = Integer.parseInt(sl);
                        }
                        catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(rootPane, "So luong nhap sai cu phap");
                            continue;
                        }
                        //kiem tra xem du so luong de ban hay khong
                        if(sl_int > s.getSl()){
                            JOptionPane.showMessageDialog(rootPane, "So luong khong du");
                            continue;
                        }
                        else{
                            TongTien_int += s.thanhtien(sl_int);
                            break;
                        }
                    }
                    while(true);

                    model.addRow(new Object[]{
                        s.getMaSach(),s.getTenSach(),s.getGia(),sl_int,currencyVN.format(s.thanhtien(sl_int))
                    });

                    lblTongTien_Nhap.setText(currencyVN.format(TongTien_int));
                    txtFind.setText("nhap ma sach");
                    txtFind.requestFocus();
                    return;
                }


            }
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ma hang nay ban da them vao danh sach mua hang\nHay chon edit de sua so luong hang mua");
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Kiem tra lai ma sach");
        return;
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
                
        if(txtFind.getText().contains("nhap ma sach")== true && evt.getKeyCode() != KeyEvent.VK_ENTER){
        String str = txtFind.getText();
        txtFind.setText(str.charAt(12) + "");
        }
        if(txtFind.getText().isEmpty()){
            txtFind.setText("nhap ma sach");
        }
    }//GEN-LAST:event_txtFindKeyReleased

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed

    }//GEN-LAST:event_txtFindActionPerformed

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String masach = txtFind.getText();
            int sl_int=0;

            if(masach.equals("nhap ma hang")){
                JOptionPane.showMessageDialog(rootPane, "Chua nhap ma hang");
                txtFind.requestFocus();
                return;
            }
            if (KiemTraSach(masach) == true){
                    for (DTOKhoSach s : list){
                    if(s.getMaSach().equals(masach)){
                        do{

                            String sl = JOptionPane.showInputDialog("Nhap so luong khach mua");
                            //Kiem tra nguoi dung co muon thoat khoi muc nhap so luong khong
                            if(sl == null){
                                txtFind.setText("nhap ma sach");
                                txtFind.requestFocus();
                                return;
                            }



                            //Cac loi sai ve so luong de de nguoi dung nhap lai so luong
                            //Kiem tra xem nguoi dung co nhap so luong la ki tu hay khong
                            try{
                                sl_int = Integer.parseInt(sl);
                            }
                            catch(NumberFormatException e){
                                JOptionPane.showMessageDialog(rootPane, "So luong nhap sai cu phap");
                                continue;
                            }
                            //kiem tra xem du so luong de ban hay khong
                            if(sl_int > s.getSl()){
                                JOptionPane.showMessageDialog(rootPane, "So luong khong du");
                                continue;
                            }
                            else{
                                TongTien_int += s.thanhtien(sl_int);
                                break;
                            }
                        }
                        while(true);

                        model.addRow(new Object[]{
                            s.getMaSach(),s.getTenSach(),s.getGia(),sl_int,currencyVN.format(s.thanhtien(sl_int))
                        });

                        lblTongTien_Nhap.setText(currencyVN.format(TongTien_int));
                        txtFind.setText("nhap ma sach");
                        txtFind.requestFocus();
                        return;
                    }


                }

            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Ma hang nay ban da them vao danh sach mua hang\nHay chon edit de sua so luong hang mua");
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Kiem tra lai ma sach");
            return;        
        }

    }//GEN-LAST:event_txtFindKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblBanSach.getSelectedRow();
        if (row == -1 ){
            JOptionPane.showMessageDialog(rootPane, "Hay chon 1 dong roi an nut xoa");
            return ;
        }
        else {
            
            
            TongTien_int -= (int) tblBanSach.getValueAt(row, 2) * (int) tblBanSach.getValueAt(row, 3);
            lblTongTien_Nhap.setText(currencyVN.format(TongTien_int));
            
            
            
            model.removeRow(row);
            txtFind.setText("nhap ma sach");
            txtFind.requestFocus();
            return ;
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblBanSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanSachMouseClicked
        // TODO add your handling code here:
        int row = tblBanSach.getSelectedRow();
        
        txtFind.setText(tblBanSach.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblBanSachMouseClicked

    private void btnAddKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKHActionPerformed
        if(txtTenKH.getText().isEmpty() || txtDiaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Khong de trong thong tin");
            return;
        }  
        DTOKhachHang s = new DTOKhachHang();
        s.setMaKH(txtSDT_NHAP.getText());
        s.setTenKH(txtTenKH.getText());
        s.setDiaChi(txtDiaChi.getText());
        s.setSDT(txtSDT_NHAP.getText());
        s.setTichDiem(0);
        list_kh.add(s);
        if(new BUSKhachHang().addKhachHang(s).equals("Thêm khách hàng thành công")){
            jpNhapThongTinKhach.setVisible(false);
            jpThongTinKhach.setVisible(true);
            btnXacNhanActionPerformed(evt);
        }
    }//GEN-LAST:event_btnAddKHActionPerformed
 
    
    
    private void GiamGia(){
        switch (Integer.parseInt(lblTichDiem.getText())){
            case 5 :{
                if(CheckGiamGia("giam 7% cho 1 hoa don") < 1){
                    lblMaGiamGia.setText("giam 7% cho 1 hoa don");
                    SoTienTra = (int) Math.round(TongTien_int - TongTien_int * 0.07) ;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra));
                }
                else{
                    lblMaGiamGia.setText("Khong ap dung");
                    SoTienTra = TongTien_int;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra));
                }
                break;
            }
            case 15 :{
                if(CheckGiamGia("giam 7% cho 3 hoa don") < 3){
                    lblMaGiamGia.setText("giam 7% cho 3 hoa don");
                    SoTienTra = (int) Math.round(TongTien_int - TongTien_int * 0.07) ;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra));
                }
                else{
                    lblMaGiamGia.setText("Khong ap dung");
                    SoTienTra = TongTien_int;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra));
                }
                break;
            }
            case 50 :{
                if(CheckGiamGia("giam 7% cho 5 hoa don") < 5){
                    lblMaGiamGia.setText("giam 7% cho 5 hoa don");
                    SoTienTra = (int) Math.round(TongTien_int - TongTien_int * 0.07) ;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra)); 
                }
                else{
                    lblMaGiamGia.setText("Khong ap dung");
                    SoTienTra = TongTien_int;
                    lblSoTienTra.setText(currencyVN.format(SoTienTra));
                }
                break;
            }
            case 100 :{
                lblMaGiamGia.setText("giam 3% cho n hoa don");
                SoTienTra = (int) Math.round(TongTien_int - TongTien_int * 0.03) ;
                lblSoTienTra.setText(currencyVN.format(SoTienTra));
                break;
            }
            default: {
                lblMaGiamGia.setText("Khong ap dung");
                SoTienTra = TongTien_int;
                lblSoTienTra.setText(currencyVN.format(SoTienTra));
            }
        }
    }
    private void btnTiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucActionPerformed
        // TODO add your handling code here:
        if(lblMaKH.getText().equals("")== true){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap thong tin khach");
            return;
        }
        
        lblMaPhieu.setText(new BUSHoaDon().getNewCode());
        lblMaKH_HD.setText(lblMaKH.getText());
        lblTenKH_HD.setText(lblTenKH.getText());
        lblTongTien.setText(lblTongTien_Nhap.getText());
        tblHoaDon.setModel(model);
        
        //ghi chi tiet thong tin phieu vao co so du lieu
        LocalDate localDate = LocalDate.now();
        String year = Integer.toString(localDate.getYear());//lay ra nam hien tai
        String day = Integer.toString(localDate.getDayOfMonth());//lay ra ngay hien tai
        String month = Integer.toString(localDate.getMonthValue());
        String date = day+"/"+month+"/"+year;
        
        lblNgayLap.setText(date);
        lblTongTien.setText(lblTongTien_Nhap.getText());
        GiamGia();
  
        
        
        
        jTabbedPane1.setSelectedIndex(2);
        
        
        
    }//GEN-LAST:event_btnTiepTucActionPerformed
    
    
    //Reset ung dung sau khi thanh toan
    private void Reset(){
        model.setRowCount(0);
        
        lblMaPhieu.setText("");
        lblDiaChiKH.setText("");
        lblMaGiamGia.setText("");
        lblMaKH.setText("");
        lblMaKH_HD.setText("");
        lblMaNV.setText(MaNV);
        lblMaPhieu.setText("");
        lblNgayLap.setText("");
        lblSDTKH.setText("");
        lblSoTienTra.setText("");
        lblTenKH.setText("");
        lblTenKH_HD.setText("");
        lblTenNV.setText(TenNV);
        lblTichDiem.setText("");
        lblTongTien.setText("");
        lblTongTien_Nhap.setText("");
        txtSDT_NHAP.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtTenKH.setText("");
        jTabbedPane1.setSelectedIndex(0);
        BangChon.setVisible(true);
        
        //Xoa cac tinh tien
        TongTien_int = 0;
        SoTienTra = 0;
        
        //Reset array list
        list = new BUSKhoSach().getAllsach();
        list_kh = new BUSKhachHang().getAllKhachHang();
        list_hd = new BUSHoaDon().getAllHoaDon();
        
    }
    
    private int CheckGiamGia(String a){
        int dem = 0;
        for (DTOHoaDon s : list_hd){
            if(s.getThongTinUuDai().equals(a) == true){
                dem ++;
            }
        }
        
        return dem;
    }
    
    private void ThucHienTichDiem(){
        int DiemDaTich = Integer.parseInt(lblTichDiem.getText());
        switch (DiemDaTich){
            case 5:{
                if(CheckGiamGia("giam 7% cho 1 hoa don") < 1){
                    return;
                }
                break;
            }
            case 15:{
                if (CheckGiamGia("giam 7% cho 3 hoa don") < 3){
                    return;
                }
                break;
            }
            case 50:{
                if(CheckGiamGia("giam 7% cho 5 hoa don") < 5){
                    return ;
                }
                break;
            }
            case 100:
                return ;
        }
        if(SoTienTra >= 200000){
            int TichDiem =  DiemDaTich + 1;
            if(new DAOKhachHang().TichDiem(TichDiem, lblMaKH_HD.getText()));
            JOptionPane.showMessageDialog(rootPane, "Khach hang duoc tich diem");
            
        }
    }
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        DTOHoaDon s = new DTOHoaDon();
        
        s.setMaHD(Integer.parseInt(lblMaPhieu.getText()));
        s.setMaKH(lblMaKH_HD.getText());
        s.setMaNV(lblMaNV.getText());
        try {
            s.setNgayLap(new SimpleDateFormat("dd/MM/yyyy").parse(lblNgayLap.getText()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        s.setThongTinUuDai(lblMaGiamGia.getText());
        s.setTongTien(SoTienTra);
        
        //Thuc hien co che tich diem
        
        ThucHienTichDiem();
        
        //Tinh toan tru SLTonKho
        
        for (int i = 0; i < tblHoaDon.getRowCount();i++){
            for (DTOKhoSach slTonKho : list){
                if(slTonKho.getMaSach().equals(tblHoaDon.getValueAt(i, 0))){
                        if(new DAOKhoSach().TruSLBanHang(slTonKho.getMaSach(), slTonKho.getSl(), (int) tblHoaDon.getValueAt(i, 3))){
                            slTonKho.setSl(slTonKho.getSl() - (int) tblHoaDon.getValueAt(i, 3));
                        }
                }
            }
        }
        
                
       
        
        JOptionPane.showMessageDialog(rootPane, new BUSHoaDon().addHoaDon(s));
            
        //Them thong tin hang vao chi tiet hoa don


        for (int i = 0; i < tblHoaDon.getRowCount(); i++){
            DTOChiTietHoaDon cthd =  new DTOChiTietHoaDon();
            cthd.setMaHoaDon(Integer.parseInt(lblMaPhieu.getText()));
            cthd.setMaSach((String) tblHoaDon.getValueAt(i, 0));
            cthd.setTenSach((String) tblHoaDon.getValueAt(i, 1));
            cthd.setGiaSach((int) tblHoaDon.getValueAt(i, 2));
            cthd.setSLMua((int) tblHoaDon.getValueAt(i, 3));
            if(new BUSChiTietHoaDon().addChiTietHoaDon(cthd).equals("Xảy ra lỗi")){
                JOptionPane.showMessageDialog(rootPane, "Xảy ra lỗi");
                new BUSChiTietHoaDon().deleteChiTietHoaDon(s);
                new BUSHoaDon().deleteHoaDon(s);
                return;
            }
        }
        
        jTabbedPane1.setSelectedIndex(0);
        Reset();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selected_row = tblBanSach.getSelectedRow();
        String masach = txtFind.getText();
        int sl_int = 0;
        if(selected_row == -1){
            JOptionPane.showMessageDialog(rootPane, "Chua chon hang de sua");
            return;
        }
        else{
            System.out.println();
             for (DTOKhoSach s : list){
                if(s.getMaSach().equals(masach)){
                    do{

                        String sl = JOptionPane.showInputDialog("Nhap so luong khach mua");
                        //Kiem tra nguoi dung co muon thoat khoi muc nhap so luong khong
                        if(sl == null){
                            txtFind.setText("nhap ma sach");
                            txtFind.requestFocus();
                            return;
                        }



                        //Cac loi sai ve so luong de de nguoi dung nhap lai so luong
                        //Kiem tra xem nguoi dung co nhap so luong la ki tu hay khong
                        try{
                            sl_int = Integer.parseInt(sl);
                        }
                        catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(rootPane, "So luong nhap sai cu phap");
                            continue;
                        }
                        //kiem tra xem du so luong de ban hay khong
                        if(sl_int > s.getSl()){
                            JOptionPane.showMessageDialog(rootPane, "So luong khong du");
                            continue;
                        }
                        else{
                            TongTien_int -=s.thanhtien(Integer.parseInt(tblBanSach.getValueAt(selected_row, 3).toString()));
                            TongTien_int += s.thanhtien(sl_int);
                            break;
                        }
                    }
                    while(true);

                    model.setValueAt(sl_int, selected_row, 3);
                    model.setValueAt(currencyVN.format(s.thanhtien(sl_int)), selected_row, 4);

                    lblTongTien_Nhap.setText(currencyVN.format(TongTien_int));
                    txtFind.setText("nhap ma sach");
                    txtFind.requestFocus();
                    return;
                }


            }
            
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jTabbedPane1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1AncestorMoved

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex() == 0){
            BangChon.setVisible(true);
        }
        else {
            BangChon.setVisible(false);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddKeyPressed

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String SDT = txtSDT.getText();
            if(SDT.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Chua nhap so dien thoai cua khach hang");
                return;
            }

            if(SDT.length() != 10){
                JOptionPane.showMessageDialog(rootPane, "So dien thoai phai co 10 chu so");
                return;
            }

            for(DTOKhachHang s : list_kh){
                if(s.getMaKH().equals(SDT)){
                    lblMaKH.setText(s.getMaKH());
                    lblTenKH.setText(s.getTenKH());
                    lblDiaChiKH.setText(s.getDiaChi());
                    lblSDTKH.setText(s.getSDT());
                    lblTichDiem.setText(Integer.toString(s.getTichDiem()));
                    jpNhapThongTinKhach.setVisible(false);
                    jpThongTinKhach.setVisible(true);
                    return;
                }
            }

            jpNhapThongTinKhach.setVisible(true);
            jpThongTinKhach.setVisible(false);
            txtSDT_NHAP.setText(SDT);
        }
    }//GEN-LAST:event_txtSDTKeyPressed

    private void lbNhanVien4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanVien4MouseClicked
        // TODO add your handling code here:
        NhanVien_View a = new NhanVien_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhanVien4MouseClicked

    private void lbBanSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanSach4MouseClicked
        // TODO add your handling code here:
        BanHang_View a = new BanHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBanSach4MouseClicked

    private void lbNhaCungCap5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhaCungCap5MouseClicked
        // TODO add your handling code here:
        NXB_View a = new NXB_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhaCungCap5MouseClicked

    private void lbPhieu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu10MouseClicked
        // TODO add your handling code here:
        PhieuNhap a = new PhieuNhap(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lbPhieu10MouseClicked

    private void lbNhapSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhapSach4MouseClicked
        // TODO add your handling code here:
        NhapHangView a = new NhapHangView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhapSach4MouseClicked

    private void lbKH11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKH11MouseClicked
        // TODO add your handling code here:
        KhachHang_View a = new KhachHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbKH11MouseClicked

    private void lblBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBill4MouseClicked
        // TODO add your handling code here:
        HoaDon_View a = new HoaDon_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBill4MouseClicked

    private void lbBookStore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBookStore4MouseClicked
        // TODO add your handling code here:
        KhoSachView a = new KhoSachView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBookStore4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHang_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHang_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHang_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHang_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHang_View(MaNV,TenNV).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BangChon;
    private javax.swing.JPanel ThanhMenu4;
    private javax.swing.JPanel TieuDe;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddKH;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTiepTuc;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpNhapThongTinKhach;
    private javax.swing.JPanel jpThongTinKhach;
    private javax.swing.JLabel lbBanSach4;
    private javax.swing.JLabel lbBookStore4;
    private javax.swing.JLabel lbKH11;
    private javax.swing.JLabel lbNhaCungCap5;
    private javax.swing.JLabel lbNhanVien4;
    private javax.swing.JLabel lbNhapSach4;
    private javax.swing.JLabel lbPhieu10;
    private javax.swing.JLabel lblBill4;
    private javax.swing.JLabel lblDiaChiKH;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblMaGiamGia;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaKH_HD;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblSDTKH;
    private javax.swing.JLabel lblSoTienTra;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenKH_HD;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTichDiem;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien_Nhap;
    private javax.swing.JTable tblBanSach;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSDT_NHAP;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables

    private String String(double SoTienTra) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
