/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import BUS.BUSNhanVien;
import DAO.DAOTaiKhoan;
import DTO.DTOTaiKhoan;
import DAO.DAONhanVien;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import DTO.DTONhanVien;

/**
 *
 * @author ASUS
 */
public class NhanVien_View extends javax.swing.JFrame {

    DefaultTableModel model;
    DefaultTableModel model1;
    ArrayList<DTONhanVien> listnv;
    ArrayList<DTOTaiKhoan> listtk;

    public NhanVien_View() {
        initComponents();
       
        setExtendedState(JFrame.MAXIMIZED_BOTH);//phat toan man hinh
        listnv = new DAONhanVien().getNhanVien();
        listtk = new DAOTaiKhoan().getListTK();

        model = (DefaultTableModel) thongtinnv.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Ten Nhan Vien", "Que Quan", "So Ngay Lam", "Cong Viec Chinh"
        });
        model1 = (DefaultTableModel) dstaikhoan.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Mật Khẩu", "Email", "Trạng Thái"
        });
        themnv.setVisible(false);

        showtable();
        showtable1();
    }

    public void showtable() {
        for (DTONhanVien s : listnv) {

            model.addRow(new Object[]{
                s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
            });
        }
    }

    public void showtable1() {
        for (DTOTaiKhoan s : listtk) {

            model1.addRow(new Object[]{
                s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BackGround = new javax.swing.JPanel();
        tabledanhsach = new javax.swing.JPanel();
        danhsach = new javax.swing.JTabbedPane();
        bangds = new javax.swing.JPanel();
        scrollthongtin = new javax.swing.JScrollPane();
        thongtinnv = new javax.swing.JTable();
        paneltaikhoan = new javax.swing.JPanel();
        scrollacount = new javax.swing.JScrollPane();
        dstaikhoan = new javax.swing.JTable();
        BangChon = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        boxsearch = new javax.swing.JComboBox<>();
        txthienthi = new javax.swing.JTextField();
        block = new javax.swing.JButton();
        unblock = new javax.swing.JButton();
        TieuDe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ThanhMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbNhanVien = new javax.swing.JLabel();
        lbBanSach = new javax.swing.JLabel();
        lbNhaCungCap1 = new javax.swing.JLabel();
        lbPhieu2 = new javax.swing.JLabel();
        lbNhapSach = new javax.swing.JLabel();
        lbPhieu3 = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        BookStore = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        themnv = new javax.swing.JPanel();
        addten = new javax.swing.JTextField();
        addhometown = new javax.swing.JTextField();
        addma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbt = new javax.swing.JButton();
        cancelbt = new javax.swing.JButton();
        setcongviec = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));

        thongtinnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        thongtinnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongtinnvMouseClicked(evt);
            }
        });
        scrollthongtin.setViewportView(thongtinnv);

        javax.swing.GroupLayout bangdsLayout = new javax.swing.GroupLayout(bangds);
        bangds.setLayout(bangdsLayout);
        bangdsLayout.setHorizontalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        bangdsLayout.setVerticalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        danhsach.addTab("thông tin nhân viên ", bangds);

        dstaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dstaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dstaikhoanMouseClicked(evt);
            }
        });
        scrollacount.setViewportView(dstaikhoan);

        javax.swing.GroupLayout paneltaikhoanLayout = new javax.swing.GroupLayout(paneltaikhoan);
        paneltaikhoan.setLayout(paneltaikhoanLayout);
        paneltaikhoanLayout.setHorizontalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE))
        );
        paneltaikhoanLayout.setVerticalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
        );

        danhsach.addTab("tài khoản", paneltaikhoan);

        javax.swing.GroupLayout tabledanhsachLayout = new javax.swing.GroupLayout(tabledanhsach);
        tabledanhsach.setLayout(tabledanhsachLayout);
        tabledanhsachLayout.setHorizontalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabledanhsachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(danhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabledanhsachLayout.setVerticalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabledanhsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(danhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BangChon.setBackground(new java.awt.Color(0, 153, 153));

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-friend.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        boxsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tìm kiếm theo tên", "tìm kiếm theo mã nhân viên", "tìm kiếm theo công việc", "tìm kiếm theo quê quán" }));
        boxsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsearchActionPerformed(evt);
            }
        });

        txthienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthienthiActionPerformed(evt);
            }
        });
        txthienthi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthienthiKeyReleased(evt);
            }
        });

        block.setBackground(new java.awt.Color(0, 204, 153));
        block.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        block.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        block.setText("block");
        block.setBorder(null);
        block.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blockItemStateChanged(evt);
            }
        });
        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });

        unblock.setBackground(new java.awt.Color(0, 204, 153));
        unblock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unblock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        unblock.setText("unblock");
        unblock.setBorder(null);
        unblock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unblockItemStateChanged(evt);
            }
        });
        unblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unblockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangChonLayout = new javax.swing.GroupLayout(BangChon);
        BangChon.setLayout(BangChonLayout);
        BangChonLayout.setHorizontalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txthienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(unblock, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        BangChonLayout.setVerticalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unblock, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TieuDe.setBackground(new java.awt.Color(153, 102, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Book Sales Software");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N

        javax.swing.GroupLayout TieuDeLayout = new javax.swing.GroupLayout(TieuDe);
        TieuDe.setLayout(TieuDeLayout);
        TieuDeLayout.setHorizontalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        TieuDeLayout.setVerticalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TieuDeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))))
        );

        ThanhMenu.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon minion.png"))); // NOI18N
        jLabel2.setText("Hi You");

        lbNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lbNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Employee.png"))); // NOI18N
        lbNhanVien.setText("Nhân Viên");
        lbNhanVien.setToolTipText("");

        lbBanSach.setBackground(new java.awt.Color(0, 204, 204));
        lbBanSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBanSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookSales.png"))); // NOI18N
        lbBanSach.setText("Bán Sách");
        lbBanSach.setOpaque(true
        );

        lbNhaCungCap1.setBackground(new java.awt.Color(255, 255, 255));
        lbNhaCungCap1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhaCungCap1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhaCungCap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Suppliers.png"))); // NOI18N
        lbNhaCungCap1.setText("Nhà Sản Xuất");

        lbPhieu2.setBackground(new java.awt.Color(255, 255, 255));
        lbPhieu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coupons.png"))); // NOI18N
        lbPhieu2.setText("Phiếu Mua Hàng");

        lbNhapSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhapSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhapSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImportBook.png"))); // NOI18N
        lbNhapSach.setText("Nhập Sách");

        lbPhieu3.setBackground(new java.awt.Color(255, 255, 255));
        lbPhieu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        lbPhieu3.setText("Khách hàng");

        lblBill.setBackground(new java.awt.Color(255, 255, 255));
        lblBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill.png"))); // NOI18N
        lblBill.setText("Hóa Đơn");

        BookStore.setBackground(new java.awt.Color(255, 255, 255));
        BookStore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookStore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookStore.png"))); // NOI18N
        BookStore.setText("Cửa Hàng Sách");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Thống Kê");

        javax.swing.GroupLayout ThanhMenuLayout = new javax.swing.GroupLayout(ThanhMenu);
        ThanhMenu.setLayout(ThanhMenuLayout);
        ThanhMenuLayout.setHorizontalGroup(
            ThanhMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBanSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhaCungCap1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
            .addComponent(lblBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BookStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThanhMenuLayout.setVerticalGroup(
            ThanhMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhapSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhaCungCap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPhieu3)
                .addGap(18, 18, 18)
                .addComponent(lbPhieu2)
                .addGap(18, 18, 18)
                .addComponent(lblBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookStore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        themnv.setBackground(new java.awt.Color(51, 255, 255));
        themnv.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), null));
        themnv.setForeground(new java.awt.Color(255, 255, 255));
        themnv.setEnabled(false);
        themnv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                themnvAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        addten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtenActionPerformed(evt);
            }
        });

        addhometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhometownActionPerformed(evt);
            }
        });

        addma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Nhân Viên");

        jLabel7.setText("Họ Và Tên");

        jLabel8.setText("Quê Quán");

        jLabel10.setText("Công Việc Chính");

        addbt.setBackground(new java.awt.Color(0, 204, 153));
        addbt.setText("Thêm");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        cancelbt.setBackground(new java.awt.Color(0, 204, 153));
        cancelbt.setText("Hủy");
        cancelbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtActionPerformed(evt);
            }
        });

        setcongviec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhan vien kho", "nhan vien ban hang" }));

        jLabel9.setText("Email");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themnvLayout = new javax.swing.GroupLayout(themnv);
        themnv.setLayout(themnvLayout);
        themnvLayout.setHorizontalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addhometown)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addma)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addten)
            .addGroup(themnvLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(setcongviec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtemail)
        );
        themnvLayout.setVerticalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themnvLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addten, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(ThanhMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BangChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(themnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                    .addGap(0, 164, Short.MAX_VALUE)
                    .addComponent(tabledanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(themnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ThanhMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                    .addGap(0, 184, Short.MAX_VALUE)
                    .addComponent(tabledanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
        themnv.setVisible(true);


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selected = thongtinnv.getSelectedRow();
        if (selected == -1) {
            JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần xóa");
        }
        String maNV = txthienthi.getText();
if (maNV != null && !maNV.trim().equals("")) {
    BUSNhanVien bus = new BUSNhanVien();
    bus.xoaNhanVien(maNV, model, model1, listnv, listtk);
    txthienthi.setText("");
}


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void boxsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxsearchActionPerformed

    private void blockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blockItemStateChanged


    }//GEN-LAST:event_blockItemStateChanged

    @SuppressWarnings("StringEquality")
    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
       // TODO add your handling code here:
       int selected = dstaikhoan.getSelectedRow();
       if (selected == -1) {
           JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần khóa tài khoản !");
           return;
       }

       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
       if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
           BUSNhanVien bus =new BUSNhanVien();
           bus.blocknhanvien(listtk, maNV);
       }

       showResult1();
    }//GEN-LAST:event_blockActionPerformed
    public void showResult1() {
        model1.setRowCount(0);
        listtk = new DAOTaiKhoan().getListTK();
        for (DTOTaiKhoan s : listtk) {
            model1.addRow(new Object[]{
                s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai()
            });
        }
    }
    private void addmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmaActionPerformed
        public boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return email.matches(regex);
    }
    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ trường văn bản

        themnv.setVisible(false);
       
       DTONhanVien nv= new DTONhanVien();
       DTOTaiKhoan tk=new DTOTaiKhoan();
        if(addbt.getText().equals("")||addhometown.getText().equals("")||addma.getText().equals("")||addten.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"mời bạn nhập đầy đủ thông tin!");
            themnv.setVisible(true);
            return;
        }
        for (DTONhanVien nhanVien : listnv) {
            if (nhanVien.getMaNV().equals(addma.getText())) { // Tìm đối tượng DTONhanVien có mã nhân viên tương ứng trong ArrayList
                JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã trùng mời bạn nhập lại !");
                themnv.setVisible(true);
                return;
            }
        }
         if (!isValidEmail(txtemail.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "email không đúng định dạng mời bạn nhập lại!");
                    themnv.setVisible(true);
                   return;
                   
                }
        nv.setMaNV(addma.getText());
        nv.setTenNV(addten.getText());
        nv.setQueQuan(addhometown.getText());
        nv.setCongViec((String) setcongviec.getSelectedItem());
        //thêm tài khoản
        tk.setMaNhanVien(addma.getText());
        tk.setEmail(txtemail.getText());
        tk.setMatKhau("1");
        tk.setTrangThai("mo");
        if (new DAONhanVien().addNhanvien(nv)&&new DAOTaiKhoan().addTaiKhoan(tk)) {

            JOptionPane.showMessageDialog(rootPane, "add success");

            listtk.add(tk);
            listnv.add(nv);
        } else if (null == nv) {
            JOptionPane.showMessageDialog(rootPane, "Student's ID cannot be duplicated");
        }
        addma.setText("");
        addten.setText("");
        addhometown.setText("");
        txtemail.setText("");
        setcongviec.setSelectedIndex(0);
       
        showResult();

    }//GEN-LAST:event_addbtActionPerformed

    public void showResult() {
        DTONhanVien s = listnv.get(listnv.size() - 1);
        model.addRow(new Object[]{
            s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
        });
         DTOTaiKhoan tk = listtk.get(listtk.size() - 1);
        model1.addRow(new Object[]{
           tk.getMaNhanVien(),tk.getMatKhau(),tk.getEmail(),tk.getTrangThai()
        });
    }
    private void themnvAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_themnvAncestorAdded

    }//GEN-LAST:event_themnvAncestorAdded

    private void cancelbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtActionPerformed
        // TODO add your handling code here:
        themnv.setVisible(false);
        tabledanhsach.setVisible(true);

    }//GEN-LAST:event_cancelbtActionPerformed

    private void thongtinnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongtinnvMouseClicked
        int selected = thongtinnv.getSelectedRow();

        txthienthi.setText((String) thongtinnv.getValueAt(selected, 0));
    }//GEN-LAST:event_thongtinnvMouseClicked

    private void addhometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addhometownActionPerformed

    private void txthienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthienthiActionPerformed

    }//GEN-LAST:event_txthienthiActionPerformed

    private void txthienthiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthienthiKeyReleased
        // TODO add your handling code here:

        // TODO add your handling code here:
        String selectedItem = boxsearch.getSelectedItem().toString();
       BUSNhanVien bus= new BUSNhanVien();
       
                thongtinnv.setModel(bus.timKiem(model, listnv, selectedItem, txthienthi.getText()));
              


    }//GEN-LAST:event_txthienthiKeyReleased

    private void dstaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstaikhoanMouseClicked
        // TODO add your handling code here:
        int selected = dstaikhoan.getSelectedRow();

        txthienthi.setText((String) dstaikhoan.getValueAt(selected, 0));
    }//GEN-LAST:event_dstaikhoanMouseClicked

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void addtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtenActionPerformed

    private void unblockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unblockItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_unblockItemStateChanged

    private void unblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unblockActionPerformed
        // TODO add your handling code here:
         int selected = dstaikhoan.getSelectedRow();
       if (selected == -1) {
           JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần mở tài khoản !");
           return;
       }

       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
       if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
           BUSNhanVien bus =new BUSNhanVien();
           bus.unblocknhanvien(listtk, maNV);
       }

       showResult1();
        
    }//GEN-LAST:event_unblockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NhanVien_View().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BangChon;
    private javax.swing.JLabel BookStore;
    private javax.swing.JPanel ThanhMenu;
    private javax.swing.JPanel TieuDe;
    private javax.swing.JButton addbt;
    private javax.swing.JTextField addhometown;
    private javax.swing.JTextField addma;
    private javax.swing.JTextField addten;
    private javax.swing.JPanel bangds;
    private javax.swing.JButton block;
    private javax.swing.JComboBox<String> boxsearch;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton cancelbt;
    private javax.swing.JTabbedPane danhsach;
    private javax.swing.JTable dstaikhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbBanSach;
    private javax.swing.JLabel lbNhaCungCap1;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbNhapSach;
    private javax.swing.JLabel lbPhieu2;
    private javax.swing.JLabel lbPhieu3;
    private javax.swing.JLabel lblBill;
    private javax.swing.JPanel paneltaikhoan;
    private javax.swing.JScrollPane scrollacount;
    private javax.swing.JScrollPane scrollthongtin;
    private javax.swing.JComboBox<String> setcongviec;
    private javax.swing.JPanel tabledanhsach;
    public javax.swing.JPanel themnv;
    private javax.swing.JTable thongtinnv;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthienthi;
    private javax.swing.JButton unblock;
    // End of variables declaration//GEN-END:variables

}
