/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import BUS.BUSKhachHang;
import BUS.BUSNhanVien;
import BUS.BUSTaiKhoan;
import DAO.DAOTaiKhoan;
import DTO.DTOTaiKhoan;
import DAO.DAONhanVien;
import DTO.DTOKhachHang;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import DTO.DTONhanVien;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import org.apache.poi.hssf.usermodel.*;
/**
 *
 * @author ASUS
 */
public class NhanVien_View extends javax.swing.JFrame {

    DefaultTableModel model;
    DefaultTableModel model1;
    ArrayList<DTONhanVien> listnv;
    ArrayList<DTOTaiKhoan> listtk;
    
    static String MaNV,TenNV;
    
    public NhanVien_View(){
        
    }
    public NhanVien_View(String MaNV,String TenNV) {
        initComponents();
       
        setExtendedState(JFrame.MAXIMIZED_BOTH);//phat toan man hinh
         listnv = new BUSNhanVien().getAllNhanVien();
        
        listtk = new BUSTaiKhoan().getAllTaiKhoan();

        model = (DefaultTableModel) thongtinnv.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Ten Nhan Vien", "Que Quan", "So Ngay Lam", "Cong Viec Chinh"
        });
        model1 = (DefaultTableModel) dstaikhoan.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Mật Khẩu", "Email", "Trạng Thái","chức vụ"
        });
        themnv.setVisible(false);

        showtable();
        showtable1();
        
        this.MaNV = MaNV;
        this.TenNV = TenNV;
        
        lblHello.setText("Hi " + this.TenNV);

    }

    public void showtable() {
        for (DTONhanVien s : listnv) {

            model.addRow(new Object[]{
                s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
            });
        }
    }

    public void showtable1() {
        for (DTOTaiKhoan s : listtk) {

            model1.addRow(new Object[]{
                s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai(),s.getChucVu()
            });
        }
    }
    private void loadDatanv(ArrayList<DTONhanVien> listnv) {
        model.setRowCount(0);
        for (DTO.DTONhanVien s : listnv) {
            model.addRow(new Object[]{
                s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
            });
        }
        thongtinnv.setModel(model);
    }
    private void loadDatatk(ArrayList<DTOTaiKhoan> listtk) {
        model1.setRowCount(0);
        for (DTOTaiKhoan s : listtk) {
            model1.addRow(new Object[]{
                s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai(),s.getChucVu()
            });
        }
        thongtinnv.setModel(model1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BackGround = new javax.swing.JPanel();
        tabledanhsach = new javax.swing.JPanel();
        danhsach = new javax.swing.JTabbedPane();
        bangds = new javax.swing.JPanel();
        scrollthongtin = new javax.swing.JScrollPane();
        thongtinnv = new javax.swing.JTable();
        paneltaikhoan = new javax.swing.JPanel();
        scrollacount = new javax.swing.JScrollPane();
        dstaikhoan = new javax.swing.JTable();
        BangChon = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        boxsearch = new javax.swing.JComboBox<>();
        txthienthi = new javax.swing.JTextField();
        block = new javax.swing.JButton();
        unblock = new javax.swing.JButton();
        btnEx = new javax.swing.JButton();
        btnIm = new javax.swing.JButton();
        TieuDe1 = new javax.swing.JPanel();
        lblThayDoiTK3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        themnv = new javax.swing.JPanel();
        addten = new javax.swing.JTextField();
        addhometown = new javax.swing.JTextField();
        addma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbt = new javax.swing.JButton();
        cancelbt = new javax.swing.JButton();
        setcongviec = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        ThanhMenu5 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        lbNhanVien5 = new javax.swing.JLabel();
        lbBanSach4 = new javax.swing.JLabel();
        lbNhaCungCap5 = new javax.swing.JLabel();
        lbPhieu10 = new javax.swing.JLabel();
        lbNhapSach4 = new javax.swing.JLabel();
        lbPhieu11 = new javax.swing.JLabel();
        lblBill4 = new javax.swing.JLabel();
        BookStore4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));

        thongtinnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        thongtinnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongtinnvMouseClicked(evt);
            }
        });
        scrollthongtin.setViewportView(thongtinnv);

        javax.swing.GroupLayout bangdsLayout = new javax.swing.GroupLayout(bangds);
        bangds.setLayout(bangdsLayout);
        bangdsLayout.setHorizontalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        bangdsLayout.setVerticalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        danhsach.addTab("thông tin nhân viên ", bangds);

        dstaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dstaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dstaikhoanMouseClicked(evt);
            }
        });
        scrollacount.setViewportView(dstaikhoan);

        javax.swing.GroupLayout paneltaikhoanLayout = new javax.swing.GroupLayout(paneltaikhoan);
        paneltaikhoan.setLayout(paneltaikhoanLayout);
        paneltaikhoanLayout.setHorizontalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE))
        );
        paneltaikhoanLayout.setVerticalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
        );

        danhsach.addTab("tài khoản", paneltaikhoan);

        javax.swing.GroupLayout tabledanhsachLayout = new javax.swing.GroupLayout(tabledanhsach);
        tabledanhsach.setLayout(tabledanhsachLayout);
        tabledanhsachLayout.setHorizontalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabledanhsachLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(danhsach))
        );
        tabledanhsachLayout.setVerticalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabledanhsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(danhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BangChon.setBackground(new java.awt.Color(0, 153, 153));

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-friend.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        boxsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tìm kiếm theo tên", "tìm kiếm theo mã nhân viên", "tìm kiếm theo công việc", "tìm kiếm theo quê quán" }));
        boxsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsearchActionPerformed(evt);
            }
        });

        txthienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthienthiActionPerformed(evt);
            }
        });
        txthienthi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthienthiKeyReleased(evt);
            }
        });

        block.setBackground(new java.awt.Color(0, 204, 153));
        block.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        block.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        block.setText("block");
        block.setBorder(null);
        block.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blockItemStateChanged(evt);
            }
        });
        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });

        unblock.setBackground(new java.awt.Color(0, 204, 153));
        unblock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unblock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unblock.png"))); // NOI18N
        unblock.setText("unblock");
        unblock.setBorder(null);
        unblock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unblockItemStateChanged(evt);
            }
        });
        unblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unblockActionPerformed(evt);
            }
        });

        btnEx.setBackground(new java.awt.Color(0, 204, 153));
        btnEx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEx.setText("Xuất file Excel");
        btnEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExActionPerformed(evt);
            }
        });

        btnIm.setBackground(new java.awt.Color(0, 204, 153));
        btnIm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIm.setText("Nhập từ file Excel");
        btnIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangChonLayout = new javax.swing.GroupLayout(BangChon);
        BangChon.setLayout(BangChonLayout);
        BangChonLayout.setHorizontalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txthienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnIm, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(unblock, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BangChonLayout.setVerticalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unblock, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(BangChonLayout.createSequentialGroup()
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEx)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TieuDe1.setBackground(new java.awt.Color(153, 102, 0));

        lblThayDoiTK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        lblThayDoiTK3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThayDoiTK3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThayDoiTK3MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Hệ thống quản lý cửa hàng sách");

        javax.swing.GroupLayout TieuDe1Layout = new javax.swing.GroupLayout(TieuDe1);
        TieuDe1.setLayout(TieuDe1Layout);
        TieuDe1Layout.setHorizontalGroup(
            TieuDe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDe1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThayDoiTK3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TieuDe1Layout.setVerticalGroup(
            TieuDe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThayDoiTK3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        themnv.setBackground(new java.awt.Color(51, 255, 255));
        themnv.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), null));
        themnv.setForeground(new java.awt.Color(255, 255, 255));
        themnv.setEnabled(false);
        themnv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                themnvAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        addten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtenActionPerformed(evt);
            }
        });

        addhometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhometownActionPerformed(evt);
            }
        });

        addma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Nhân Viên");

        jLabel7.setText("Họ Và Tên");

        jLabel8.setText("Quê Quán");

        jLabel10.setText("Công Việc Chính");

        addbt.setBackground(new java.awt.Color(0, 204, 153));
        addbt.setText("Thêm");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        cancelbt.setBackground(new java.awt.Color(0, 204, 153));
        cancelbt.setText("Hủy");
        cancelbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtActionPerformed(evt);
            }
        });

        setcongviec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhan vien kho", "nhan vien ban hang" }));

        jLabel9.setText("Email");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themnvLayout = new javax.swing.GroupLayout(themnv);
        themnv.setLayout(themnvLayout);
        themnvLayout.setHorizontalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addhometown)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addma)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addten)
            .addGroup(themnvLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(setcongviec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtemail)
        );
        themnvLayout.setVerticalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themnvLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addten, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThanhMenu5.setBackground(new java.awt.Color(0, 153, 153));

        lblHello.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon minion.png"))); // NOI18N
        lblHello.setText("Hi You");
        lblHello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHello.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbNhanVien5.setBackground(new java.awt.Color(0, 204, 204));
        lbNhanVien5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanVien5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Employee.png"))); // NOI18N
        lbNhanVien5.setText("  Nhân viên");
        lbNhanVien5.setToolTipText("");
        lbNhanVien5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhanVien5.setOpaque(true
        );
        lbNhanVien5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanVien5MouseClicked(evt);
            }
        });

        lbBanSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbBanSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBanSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookSales.png"))); // NOI18N
        lbBanSach4.setText("  Bán sách");
        lbBanSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBanSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanSach4MouseClicked(evt);
            }
        });

        lbNhaCungCap5.setBackground(new java.awt.Color(0, 204, 204));
        lbNhaCungCap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhaCungCap5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhaCungCap5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Suppliers.png"))); // NOI18N
        lbNhaCungCap5.setText("  Nhà xuất bản");
        lbNhaCungCap5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhaCungCap5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhaCungCap5MouseClicked(evt);
            }
        });

        lbPhieu10.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coupons.png"))); // NOI18N
        lbPhieu10.setText("  Phiếu nhập");
        lbPhieu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu10MouseClicked(evt);
            }
        });

        lbNhapSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhapSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhapSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhapSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImportBook.png"))); // NOI18N
        lbNhapSach4.setText("  Nhập sách");
        lbNhapSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhapSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhapSach4MouseClicked(evt);
            }
        });

        lbPhieu11.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        lbPhieu11.setText("  Khách hàng");
        lbPhieu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu11MouseClicked(evt);
            }
        });

        lblBill4.setBackground(new java.awt.Color(0, 204, 204));
        lblBill4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBill4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill.png"))); // NOI18N
        lblBill4.setText("  Hóa đơn");
        lblBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBill4MouseClicked(evt);
            }
        });

        BookStore4.setBackground(new java.awt.Color(0, 204, 204));
        BookStore4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookStore4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookStore4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookStore.png"))); // NOI18N
        BookStore4.setText(" Cửa hàng sách");
        BookStore4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookStore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookStore4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThanhMenu5Layout = new javax.swing.GroupLayout(ThanhMenu5);
        ThanhMenu5.setLayout(ThanhMenu5Layout);
        ThanhMenu5Layout.setHorizontalGroup(
            ThanhMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBanSach4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhanVien5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapSach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhaCungCap5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBill4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhMenu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookStore4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThanhMenu5Layout.setVerticalGroup(
            ThanhMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhMenu5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhanVien5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhapSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhaCungCap5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPhieu11)
                .addGap(18, 18, 18)
                .addComponent(lbPhieu10)
                .addGap(18, 18, 18)
                .addComponent(lblBill4)
                .addGap(18, 18, 18)
                .addComponent(BookStore4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(ThanhMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TieuDe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BangChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(tabledanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(themnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(TieuDe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(themnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabledanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(ThanhMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
        themnv.setVisible(true);


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selected = thongtinnv.getSelectedRow();
        if (selected == -1) {
            JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần xóa");
        }
        String maNV = txthienthi.getText();
if (maNV != null && !maNV.trim().equals("")) {
   DTONhanVien nv = null;
        DTOTaiKhoan tk = null;
        for (DTONhanVien nhanVien : listnv) {
            if (nhanVien.getMaNV().equals(maNV)) { // Tìm đối tượng DTONhanVien có mã nhân viên tương ứng trong ArrayList
                nv = nhanVien;
                break;
            }
        }
        for (DTOTaiKhoan taikhoan : listtk) {
            if (taikhoan.getMaNhanVien().equals(maNV)) { // Tìm đối tượng DTONhanVien có mã nhân viên tương ứng trong ArrayList
                tk = taikhoan;
                break;
            }
        }
        if (nv != null) { // Nếu tìm thấy đối tượng DTONhanVien
           // Update dữ liệu trong CSDL SQL
               new BUSNhanVien().xoaNhanVien(nv);
               
               new BUSTaiKhoan().xoatTaiKhoan(tk);
               
                int index = listnv.indexOf(nv); // Tìm vị trí của đối tượng DTONhanVien trong ArrayList
                listnv.remove(index); // Xóa đối tượng DTONhanVien khỏi ArrayList
                model.removeRow(index); // Xóa dòng tương ứng trong table 
                int index1 = listtk.indexOf(tk); // Tìm vị trí của đối tượng taikhoan trong ArrayList
                listtk.remove(index1); // Xóa đối tượng taikhoan khỏi ArrayList
                model1.removeRow(index1); // Xóa dòng tương ứng trong table 
               JOptionPane.showMessageDialog(rootPane, "xóa thành công");
           
        }
    txthienthi.setText("");
}


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void boxsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxsearchActionPerformed

    private void blockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blockItemStateChanged


    }//GEN-LAST:event_blockItemStateChanged

    @SuppressWarnings("StringEquality")
    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
       // TODO add your handling code here:
       int selected = dstaikhoan.getSelectedRow();
       if (selected == -1) {
           JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần khóa tài khoản !");
           return;
       }
         
       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
       if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
         DTOTaiKhoan tk = null;
           for (DTOTaiKhoan taikhoan : listtk) {
               if (taikhoan.getTrangThai().equalsIgnoreCase("mo") && taikhoan.getMaNhanVien().equals(maNV)) {
                   tk = taikhoan;
                   break;
               } else if (taikhoan.getTrangThai().equalsIgnoreCase("khóa")&& taikhoan.getMaNhanVien().equals(maNV)) {
                   JOptionPane.showMessageDialog(rootPane, "tài khoản này đã khóa!");
                    break;
               }
           }
           if (tk != null) { // Nếu tìm thấy đối tượng DTONhanVien
               new BUSTaiKhoan().khoaTaiKhoan(tk);
             
                    txthienthi.setText("");
              
           }
       }

       showResult1();
    }//GEN-LAST:event_blockActionPerformed
    public void showResult1() {
        model1.setRowCount(0);
        listtk = new DAOTaiKhoan().getListTK();
        for (DTOTaiKhoan s : listtk) {
            model1.addRow(new Object[]{
                s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai(),s.getChucVu()
            });
        }
    }
    private void addmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmaActionPerformed
        public boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return email.matches(regex);
    }
    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ trường văn bản

        themnv.setVisible(false);
       
        DTONhanVien nv= new DTONhanVien();
       DTOTaiKhoan tk=new DTOTaiKhoan();
        if(addbt.getText().equals("")||addhometown.getText().equals("")||addma.getText().equals("")||addten.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"mời bạn nhập đầy đủ thông tin!");
            themnv.setVisible(true);
            return;
        }
        for (DTONhanVien nhanVien : listnv) {
            if (nhanVien.getMaNV().equals(addma.getText())) { // Tìm đối tượng DTONhanVien có mã nhân viên tương ứng trong ArrayList
                JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã trùng mời bạn nhập lại !");
                themnv.setVisible(true);
                return;
            }
        }
         if (!isValidEmail(txtemail.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "email không đúng định dạng mời bạn nhập lại!");
                    themnv.setVisible(true);
                   return;
                   
                }
        nv.setMaNV(addma.getText());
        nv.setTenNV(addten.getText());
        nv.setQueQuan(addhometown.getText());
        nv.setCongViec((String) setcongviec.getSelectedItem());
        //thêm tài khoản
        tk.setMaNhanVien(addma.getText());
        tk.setEmail(txtemail.getText());
        tk.setMatKhau("1");
        tk.setTrangThai("mo");
        
        new BUSNhanVien().themNhanVien(nv);
        new BUSTaiKhoan().themTaiKhoan(tk);
           
            listtk.add(tk);
            listnv.add(nv);
         JOptionPane.showMessageDialog(rootPane, "add success");
        addma.setText("");
        addten.setText("");
        addhometown.setText("");
        txtemail.setText("");
        setcongviec.setSelectedIndex(0);
       
        showResult();

    }//GEN-LAST:event_addbtActionPerformed

    public void showResult() {
        DTONhanVien s = listnv.get(listnv.size() - 1);
        model.addRow(new Object[]{
            s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
        });
         DTOTaiKhoan tk = listtk.get(listtk.size() - 1);
        model1.addRow(new Object[]{
           tk.getMaNhanVien(),tk.getMatKhau(),tk.getEmail(),tk.getTrangThai()
        });
    }
    private void themnvAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_themnvAncestorAdded

    }//GEN-LAST:event_themnvAncestorAdded

    private void cancelbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtActionPerformed
        // TODO add your handling code here:
        themnv.setVisible(false);
        tabledanhsach.setVisible(true);

    }//GEN-LAST:event_cancelbtActionPerformed

    private void thongtinnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongtinnvMouseClicked
        int selected = thongtinnv.getSelectedRow();

        txthienthi.setText((String) thongtinnv.getValueAt(selected, 0));
    }//GEN-LAST:event_thongtinnvMouseClicked

    private void addhometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addhometownActionPerformed

    private void txthienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthienthiActionPerformed

    }//GEN-LAST:event_txthienthiActionPerformed

    private void txthienthiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthienthiKeyReleased
        // TODO add your handling code here:

        // TODO add your handling code here:
        String selectedItem = boxsearch.getSelectedItem().toString();
     switch (selectedItem) {
            case "tìm kiếm theo tên":
                model.setRowCount(0);
                for (DTONhanVien nv : listnv) {
                    if (nv.getTenNV().contains(txthienthi.getText())) {
                        Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(), nv.getCongViec()};
                        model.addRow(rowData);
                    }
                }
                break;

            case "tìm kiếm theo quê quán":
                model.setRowCount(0);
                for (DTONhanVien nv : listnv) {
                    if (nv.getQueQuan().contains(txthienthi.getText())) {
                        Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(), nv.getCongViec()};
                        model.addRow(rowData);
                    }
                }
                break;
            case "tìm kiếm theo công việc":
                model.setRowCount(0);
                for (DTONhanVien nv : listnv) {
                    if (nv.getCongViec().contains(txthienthi.getText())) {
                        Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(), nv.getCongViec()};
                        model.addRow(rowData);
                    }
                }
                break;
            case "tìm kiếm theo mã nhân viên":
                model.setRowCount(0);
                for (DTONhanVien nv : listnv) {
                    if (nv.getMaNV().contains(txthienthi.getText())) {
                        Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(), nv.getCongViec()};
                        model.addRow(rowData);
                    }
                }
                break;
        }
    }//GEN-LAST:event_txthienthiKeyReleased

    private void dstaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstaikhoanMouseClicked
        // TODO add your handling code here:
        int selected = dstaikhoan.getSelectedRow();

        txthienthi.setText((String) dstaikhoan.getValueAt(selected, 0));
    }//GEN-LAST:event_dstaikhoanMouseClicked

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void addtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtenActionPerformed

    private void unblockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unblockItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_unblockItemStateChanged

    private void unblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unblockActionPerformed
        // TODO add your handling code here:
           int selected = dstaikhoan.getSelectedRow();
       if (selected == -1) {
           JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần mở tài khoản !");
           return;
       }

       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
       if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
            DTOTaiKhoan tk = null;
           for (DTOTaiKhoan taikhoan : listtk) {
               if (taikhoan.getTrangThai().equalsIgnoreCase("khóa") && taikhoan.getMaNhanVien().equals(maNV)) {
                   tk = taikhoan;
                   break;
               } else if (taikhoan.getTrangThai().equalsIgnoreCase("mo") && taikhoan.getMaNhanVien().equals(maNV)) {
                   JOptionPane.showMessageDialog(rootPane, "tài khoản này đang mở!");
                    txthienthi.setText("");
                  break;
               }
           }
           if (tk != null) { // Nếu tìm thấy đối tượng DTONhanVien

              new BUSTaiKhoan().moTaiKhoan(tk);
                 txthienthi.setText("");

              
           }
       }


       showResult1();
        
    }//GEN-LAST:event_unblockActionPerformed

    private void lbNhanVien5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanVien5MouseClicked
        // TODO add your handling code here:
        NhanVien_View a = new NhanVien_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhanVien5MouseClicked

    private void lbBanSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanSach4MouseClicked
        // TODO add your handling code here:
        BanHang_View a = new BanHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBanSach4MouseClicked

    private void lbNhaCungCap5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhaCungCap5MouseClicked
        // TODO add your handling code here:
        NXB_View a = new NXB_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhaCungCap5MouseClicked

    private void lbPhieu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu10MouseClicked
        // TODO add your handling code here:
        PhieuNhap a = new PhieuNhap(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPhieu10MouseClicked

    private void lbNhapSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhapSach4MouseClicked
        // TODO add your handling code here:
        NhapHangView a = new NhapHangView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhapSach4MouseClicked

    private void lbPhieu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu11MouseClicked
        // TODO add your handling code here:
        KhachHang_View a = new KhachHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPhieu11MouseClicked

    private void lblBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBill4MouseClicked
        // TODO add your handling code here:
        HoaDon_View a = new HoaDon_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBill4MouseClicked

    private void BookStore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookStore4MouseClicked
        // TODO add your handling code here:
        KhoSachView a = new KhoSachView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookStore4MouseClicked

    private void lblThayDoiTK3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThayDoiTK3MouseClicked
        // TODO add your handling code here:
        SuaTaiKhoan a = new SuaTaiKhoan(MaNV,TenNV);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        //this.setVisible(true);
    }//GEN-LAST:event_lblThayDoiTK3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExActionPerformed
        // TODO add your handling code here:
        XSSFWorkbook wordbook = new XSSFWorkbook();
        XSSFSheet sheet = wordbook.createSheet("Thông tin nhân viên");
        XSSFSheet sheet_tk = wordbook.createSheet("Tài khoản nhân viên");
        try{
            //Ghi sheet hoa don
            XSSFRow row = null;
            Cell cell = null;

            //Thanh tieu de
            row = sheet.createRow(0);
            cell = row.createCell(0,CellType.STRING);
            cell.setCellValue("Mã nhân viên");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên nhân viên");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Quê quán");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số ngày làm");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Công việc");

           

            //Ghi sheet chi tiet hoa don
            XSSFRow row_cthd = null;
            Cell cell_tk = null;

            //Thanh tieu de
            row_cthd = sheet_tk.createRow(0);
            cell_tk = row_cthd.createCell(0,CellType.STRING);
            cell_tk.setCellValue("Mã nhân viên");

            cell_tk= row_cthd.createCell(1, CellType.STRING);
            cell_tk.setCellValue("Mật khẩu");

            cell_tk = row_cthd.createCell(2, CellType.STRING);
            cell_tk.setCellValue("Email");

            cell_tk = row_cthd.createCell(3, CellType.STRING);
            cell_tk.setCellValue("Trạng thái");

            cell_tk = row_cthd.createCell(4, CellType.STRING);
            cell_tk.setCellValue("Chức vụ");

            int j = 0;

            for(int i=0;i<thongtinnv.getRowCount();i++){
                row = sheet.createRow(1+i);

                cell = row.createCell(0,CellType.STRING);
                cell.setCellValue(thongtinnv.getValueAt(i, 0).toString());

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(thongtinnv.getValueAt(i, 1).toString());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(thongtinnv.getValueAt(i, 2).toString());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(thongtinnv.getValueAt(i, 3).toString());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(thongtinnv.getValueAt(i, 4).toString());

                

                for(DTOTaiKhoan s : listtk){
                    if(s.getMaNhanVien().equals(thongtinnv.getValueAt(i, 0).toString())){
                        row_cthd = sheet_tk.createRow(1+j);

                        cell_tk = row_cthd.createCell(0,CellType.STRING);
                        cell_tk.setCellValue(s.getMaNhanVien());

                        cell_tk = row_cthd.createCell(1, CellType.STRING);
                        cell_tk.setCellValue(s.getMatKhau());

                        cell_tk = row_cthd.createCell(2, CellType.STRING);
                        cell_tk.setCellValue(s.getEmail());

                        cell_tk = row_cthd.createCell(3, CellType.STRING);
                        cell_tk.setCellValue(s.getTrangThai());
                        
                        cell_tk = row_cthd.createCell(4,CellType.STRING);
                        cell_tk.setCellValue(s.getChucVu());
                        j++;
                    }

                }
            }

        }
        catch(Exception e){
            e.printStackTrace();
        }

        //Thao tác kiểm tra file
        String tenfile = JOptionPane.showInputDialog("Nhập tên file ");
        if(tenfile == null){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên file");
            return;
        }
        else if (tenfile.contains(" ")){
            JOptionPane.showMessageDialog(rootPane, "Tên file không có khoảng trắng");
            return;
        }
        else if (tenfile.contains("/") || tenfile.contains("%") || tenfile.contains("#") || tenfile.contains(":") ||tenfile.contains(";") ||tenfile.contains("~") ||tenfile.contains(".") ){
            JOptionPane.showMessageDialog(rootPane, "Tên file không chứa kí tự đặc biệt");
        }

        //Thực hiện ghi file
        JFileChooser  j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        j.showSaveDialog(btnEx);
        File f = new File(j.getSelectedFile()+"\\"+tenfile+".xlsx");
            if(f.exists()){
                if(JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn ghi đè lên file này không ?") != JOptionPane.YES_OPTION){
                    return;
                }
            }
            try{
                FileOutputStream fis = new FileOutputStream(f);
                wordbook.write(fis);
                fis.close();
            }
            catch(Exception e){
                e.printStackTrace();
                return;
            }

            JOptionPane.showMessageDialog(rootPane, "Xuất file thành công");
    }//GEN-LAST:event_btnExActionPerformed

    private void btnImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImActionPerformed
       
              File excelFile;
        FileInputStream fis = null;
        BufferedInputStream bis = null;
        
        JFileChooser filechooser = new JFileChooser();
//      chỉ chọn file Excel
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILE", "xls","xlsx","xlsm");
        filechooser.setFileFilter(fnef);
//     set tiêu đề
        filechooser.setDialogTitle("Chọn file excel");
        int excelChooser = filechooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = filechooser.getSelectedFile();
                fis = new FileInputStream(excelFile);
                bis = new BufferedInputStream(fis);
                XSSFWorkbook wb = new XSSFWorkbook(bis);
                XSSFSheet sheet = wb.getSheetAt(0);
                XSSFSheet sheet1 = wb.getSheetAt(1);
                for (int row = 0; row <= sheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = sheet.getRow(row);
                    
                    XSSFCell excelManv = excelRow.getCell(0); // Lấy ô đầu tiên trong hàng
                    XSSFCell excelTennv = excelRow.getCell(1);
                    XSSFCell excelQuequan = excelRow.getCell(2);
                    XSSFCell excelSongaylam = excelRow.getCell(3);
                    XSSFCell excelCongviec = excelRow.getCell(4);
                    if (row == 0) {
                        if (!excelManv.getStringCellValue().equalsIgnoreCase("Mã nhân viên")
                                || !excelTennv.getStringCellValue().equalsIgnoreCase("Tên nhân viên")
                                || !excelQuequan.getStringCellValue().equalsIgnoreCase("Quê quán")
                                || !excelSongaylam.getStringCellValue().equalsIgnoreCase("Số ngày làm")
                                || !excelCongviec.getStringCellValue().equalsIgnoreCase("Công việc")) {
                            JOptionPane.showMessageDialog(null, "File không đúng định dạng");
                            return;
                        }
                        continue;
                    }
                     String manv = "";
                    if (excelManv.getCellType() == CellType.NUMERIC) {
                        int manvNum = (int) excelManv.getNumericCellValue();
                        manv = Integer.toString(manvNum);
                    } else {
                        manv = excelManv.getStringCellValue().trim();
                    }

                    String Tennv = excelTennv.getStringCellValue().trim();
                    String quequan = excelQuequan.getStringCellValue().trim();
                    String congviec = excelCongviec.getStringCellValue().trim();
                    
                    int obj= ktrmanv(manv);
                    
                    if(obj==-1){
                            //add
                            DTONhanVien nv =new DTONhanVien(manv, Tennv, quequan, 0,congviec);
                           
                            listnv.add(nv);
                            //them vao DB
                            new BUSNhanVien().themNhanVien(nv);
                            
                    } else {
                        
                        updateNV(Tennv, quequan, congviec, obj);
                            new BUSNhanVien().updateNhanVien(Tennv, Tennv, quequan,0, congviec);
                    }
                         
                    
                }
                 for (int row = 0; row <= sheet1.getLastRowNum(); row++) {
                    XSSFRow excelRow = sheet1.getRow(row);
                    
                    XSSFCell excelManv = excelRow.getCell(0); // Lấy ô đầu tiên trong hàng
                    XSSFCell excelMatkhau = excelRow.getCell(1);
                    XSSFCell excelEmail = excelRow.getCell(2);
                    XSSFCell excelTrangthai = excelRow.getCell(3);
                    XSSFCell excelChucvu= excelRow.getCell(4);
                    if (row == 0) {
                        if (!excelManv.getStringCellValue().equalsIgnoreCase("Mã nhân viên")
                                || !excelMatkhau.getStringCellValue().equalsIgnoreCase("Mật khẩu")
                                || !excelEmail.getStringCellValue().equalsIgnoreCase("Email")
                                || !excelTrangthai.getStringCellValue().equalsIgnoreCase("Trạng thái")
                                || !excelChucvu.getStringCellValue().equalsIgnoreCase("Chức vụ")) {
                            JOptionPane.showMessageDialog(null, "File không đúng định dạng");
                            return;
                        }
                        continue;
                    }
                     String manv = "";
                    if (excelManv.getCellType() == CellType.NUMERIC) {
                        int manvNum = (int) excelManv.getNumericCellValue();
                        manv = Integer.toString(manvNum);
                    } else {
                        manv = excelManv.getStringCellValue().trim();
                    }

                    String matkhau = "";
                    if (excelMatkhau.getCellType() == CellType.NUMERIC) {
                        int matkhaunum = (int) excelMatkhau.getNumericCellValue();
                        matkhau = Integer.toString(matkhaunum);
                    } else {
                        matkhau = excelMatkhau.getStringCellValue().trim();
                    }
                    String email = excelEmail.getStringCellValue().trim();
                    String trangthai = excelTrangthai.getStringCellValue().trim();
                    String chucvu = excelChucvu.getStringCellValue().trim();
                    
                    int obj= ktrtaikhoan(manv);
                            
                    if(obj==-1){
                        
                            DTOTaiKhoan tk  =new DTOTaiKhoan(manv, matkhau, email, trangthai, chucvu);
                           
                            listtk.add(tk);
                            //them vao DB
                            new BUSTaiKhoan().addTaiKhoan(tk);
                     }else {
                        
                        new BUSTaiKhoan().updateTaiKhoan(manv, matkhau, email, trangthai);
                        listtk =new BUSTaiKhoan().getAllTaiKhoan();
                    }
                    
                    
                         
                    
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NhanVien_View.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NhanVien_View.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (fis != null) {
                    try {
                        fis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(NhanVien_View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (bis != null) {
                    try {
                        bis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(NhanVien_View.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
              
            }
            loadDatanv(listnv);
             loadDatatk(listtk);
        }
 
    }//GEN-LAST:event_btnImActionPerformed
      private int ktrmanv (String manv){
          for(DTONhanVien nv: listnv)
              if (nv.getMaNV().equalsIgnoreCase(manv))
                 return listnv.indexOf(nv);
     return -1;
      
      }
      private int ktrtaikhoan (String manv){
          for(DTOTaiKhoan tk: listtk)
              if (tk.getMaNhanVien().equalsIgnoreCase(manv))
                 return listtk.indexOf(tk);
     return -1;
      }
    private void updateNV(String Tennv, String quequan, String chucvu,int index) {
        listnv.get(index).setTenNV(Tennv);
        listnv.get(index).setQueQuan(quequan);
        listnv.get(index).setSoNgayLam(0);
        listnv.get(index).setCongViec(chucvu);
    }
    
    
   
    private int ktManv(String manv) {
        for (DTONhanVien i : listnv) {
            if (i.getMaNV().equals(manv)) {
                return listnv.indexOf(i);
            }
        }
        return -1;
    }

    private void updateNV(int Manv, String Tennv, String quequan, String Congviec) {
        listnv.get(Manv).setTenNV(Tennv);
        listnv.get(Manv).setQueQuan(quequan);
        listnv.get(Manv).setCongViec(Congviec);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-old>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NhanVien_View(MaNV,TenNV).setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BangChon;
    private javax.swing.JLabel BookStore4;
    private javax.swing.JPanel ThanhMenu5;
    private javax.swing.JPanel TieuDe1;
    private javax.swing.JButton addbt;
    private javax.swing.JTextField addhometown;
    private javax.swing.JTextField addma;
    private javax.swing.JTextField addten;
    private javax.swing.JPanel bangds;
    private javax.swing.JButton block;
    private javax.swing.JComboBox<String> boxsearch;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEx;
    private javax.swing.JButton btnIm;
    private javax.swing.JButton cancelbt;
    private javax.swing.JTabbedPane danhsach;
    private javax.swing.JTable dstaikhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbBanSach4;
    private javax.swing.JLabel lbNhaCungCap5;
    private javax.swing.JLabel lbNhanVien5;
    private javax.swing.JLabel lbNhapSach4;
    private javax.swing.JLabel lbPhieu10;
    private javax.swing.JLabel lbPhieu11;
    private javax.swing.JLabel lblBill4;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblThayDoiTK3;
    private javax.swing.JPanel paneltaikhoan;
    private javax.swing.JScrollPane scrollacount;
    private javax.swing.JScrollPane scrollthongtin;
    private javax.swing.JComboBox<String> setcongviec;
    private javax.swing.JPanel tabledanhsach;
    public javax.swing.JPanel themnv;
    private javax.swing.JTable thongtinnv;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthienthi;
    private javax.swing.JButton unblock;
    // End of variables declaration//GEN-END:variables

}
