/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAOPhieuNhap;
import DAO.DAOChiTietPhieuNhap;
import DTO.DTOPhieuNhap;
import DTO.DTOChiTietPhieuNhap;
import BUS.BUSPhieuNhap;
import BUS.BUSChiTietPhieuNhap;
import BUS.BUSTaiKhoan;
import DAO.DAOKhoSach;
import DAO.DAONhaXuatBan;
import DTO.DTOKhoSach;
import DTO.DTONhaXuatBan;
import DTO.DTOTaiKhoan;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Currency;
import java.util.Locale;
import java.util.Random;
import javax.management.modelmbean.ModelMBean;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author ASUS
 */
public class NhapHangView extends javax.swing.JFrame {

    DefaultTableModel model_kho;
    DefaultTableModel model_nhap;
    String NXB;
    int a;
    ArrayList<DTOKhoSach> list;
    ArrayList<DTONhaXuatBan> list_NXB;
    ArrayList<DTOTaiKhoan> list_tk = new BUSTaiKhoan().getAllTaiKhoan();
    int tongtien=0;
    Locale localVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localVN);
    
    static String MaNV,TenNV;
    /**
     * Creates new form NhapHang
     */
    public NhapHangView(String MaNV, String TenNV) {
        initComponents();
        String[] header_kho = {"Ma sach", "Ten sach", "Nam xuat ban", "Ten tac gia", "Nha xuat ban", "So luong", "Gia", "The loai"};
        model_kho = new DefaultTableModel(header_kho, 0);
        String[] header_nhap = {"Ma sach", "Ten sach", "So luong", "Gia", "Thanh tien"};
        model_nhap = new DefaultTableModel(header_nhap, 0);
        setExtendedState(JFrame.MAXIMIZED_BOTH);//phat toan man hinh

        tbKho.setModel(model_kho);
        tbNhap.setModel(model_nhap);
//        txtFind.setText("Nhap nha xuat ban");
        list = new DAOKhoSach().getListSach();
        list_NXB = new DAONhaXuatBan().getListNXB();
        for(DTONhaXuatBan s : list_NXB){
            cbxNXB.addItem(s.getTen());
        }
        txtFind.setEnabled(false);
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnConfirm.setEnabled(false);
        
        tblPhieuNhap.setEnabled(false);
        //Reset();
        jTabbedPane1.setEnabledAt(1, false);
        
        this.MaNV = MaNV;
        this.TenNV = TenNV;
        
        lblHello.setText("Hi " + this.TenNV);
        
        
        for(DTOTaiKhoan s : list_tk){
            if(s.getMaNhanVien().equals(MaNV)){
                if(s.getChucVu().equals("nhan vien kho")){
                    System.out.println(s.getChucVu());
                    lbNhaCungCap5.setVisible(false);
                    lbNhanVien4.setVisible(false);
                    lbBanSach4.setVisible(false);
                    lbKH11.setVisible(false);
                    lbBookStore4.setVisible(false);
                    lblBill4.setVisible(false);
                    lbPhieu10.setVisible(false);
                }
            }
        }
        
        Reset();

    }

    public void ShowTableKho() {
        model_kho.setRowCount(0);
        list = new DAOKhoSach().getListSach();
        for (DTOKhoSach s : list) {
            if (s.getTenSach() == null) {
                continue;
            } else {
                if (s.getNhaXuatBan().equals(NXB)) {
                    model_kho.addRow(
                            new Object[]{
                                s.getMaSach(), s.getTenSach(), s.getNam(), s.getTenTacGia(), s.getNhaXuatBan(), s.getSl(), currencyVN.format(s.getGia()), s.getTheLoai()
                            }
                    );
                }
            }
        }
    }

    public void ShowTableNhap() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        BackGround = new javax.swing.JPanel();
        BangChon = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbxNXB = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpThongTinSanPham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKho = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhap = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpChiTietHoaDon = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTongHoaDon = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        ThanhMenu4 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        lbNhanVien4 = new javax.swing.JLabel();
        lbBanSach4 = new javax.swing.JLabel();
        lbNhaCungCap5 = new javax.swing.JLabel();
        lbPhieu10 = new javax.swing.JLabel();
        lbNhapSach4 = new javax.swing.JLabel();
        lbKH11 = new javax.swing.JLabel();
        lblBill4 = new javax.swing.JLabel();
        lbBookStore4 = new javax.swing.JLabel();
        TieuDe2 = new javax.swing.JPanel();
        lblThayDoiTK3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));
        BackGround.setPreferredSize(new java.awt.Dimension(1536, 864));

        BangChon.setBackground(new java.awt.Color(0, 153, 153));

        btnDelete.setBackground(new java.awt.Color(0, 204, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtFind.setForeground(new java.awt.Color(153, 153, 153));
        txtFind.setText("Nhập thông tin để tìm kiếm");
        txtFind.setToolTipText("");
        txtFind.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFindFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFindFocusLost(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 204, 153));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nhà xuất bản:");

        cbxNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbxNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNXBActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-to-basket.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangChonLayout = new javax.swing.GroupLayout(BangChon);
        BangChon.setLayout(BangChonLayout);
        BangChonLayout.setHorizontalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFind)
                .addGap(48, 48, 48)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangChonLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangChonLayout.createSequentialGroup()
                        .addComponent(cbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        BangChonLayout.setVerticalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BangChonLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtFind))
                .addContainerGap())
        );

        tbKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKho);

        tbNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbNhap);

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Bảng kho sách");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Bảng nhập sách");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("TỔNG TIỀN:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien.setText("0");

        javax.swing.GroupLayout jpThongTinSanPhamLayout = new javax.swing.GroupLayout(jpThongTinSanPham);
        jpThongTinSanPham.setLayout(jpThongTinSanPhamLayout);
        jpThongTinSanPhamLayout.setHorizontalGroup(
            jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE))
                    .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                        .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpThongTinSanPhamLayout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 270, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThongTinSanPhamLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jpThongTinSanPhamLayout.setVerticalGroup(
            jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThongTinSanPhamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThongTinSanPhamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                        .addGroup(jpThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblTongTien)
                            .addComponent(btnConfirm))
                        .addGap(46, 46, 46))))
        );

        jTabbedPane1.addTab("Thông tin sản phẩm", jpThongTinSanPham);

        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá", "Thành tiền"
            }
        ));
        jScrollPane3.setViewportView(tblPhieuNhap);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Chi tiết phiếu nhập");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Mã phiếu nhập :");

        lblMaPhieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMaPhieu.setText("123");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Ngày lập :");

        lblNgayNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNgayNhap.setText("1/2/2023");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Mã nhân viên :");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMaNV.setText("001");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Tên nhân viên :");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTenNV.setText("Lê Hoài Nam");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Tổng tiền phiếu nhập:");

        lblTongHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongHoaDon.setText("100.000.000");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpChiTietHoaDonLayout = new javax.swing.GroupLayout(jpChiTietHoaDon);
        jpChiTietHoaDon.setLayout(jpChiTietHoaDonLayout);
        jpChiTietHoaDonLayout.setHorizontalGroup(
            jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(19, 19, 19)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                .addGap(545, 545, 545)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpChiTietHoaDonLayout.setVerticalGroup(
            jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpChiTietHoaDonLayout.createSequentialGroup()
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblMaPhieu))
                        .addGap(29, 29, 29)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblNgayNhap))
                        .addGap(30, 30, 30)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblMaNV))
                        .addGap(32, 32, 32)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblTenNV))
                        .addGap(37, 37, 37)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblTongHoaDon))
                        .addGap(69, 69, 69)
                        .addGroup(jpChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chi tiết phiếu nhập", jPanel5);

        ThanhMenu4.setBackground(new java.awt.Color(0, 153, 153));

        lblHello.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon minion.png"))); // NOI18N
        lblHello.setText("Hi You");
        lblHello.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHello.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbNhanVien4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhanVien4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanVien4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Employee.png"))); // NOI18N
        lbNhanVien4.setText("  Nhân viên");
        lbNhanVien4.setToolTipText("");
        lbNhanVien4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhanVien4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanVien4MouseClicked(evt);
            }
        });

        lbBanSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbBanSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBanSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookSales.png"))); // NOI18N
        lbBanSach4.setText("  Bán sách");
        lbBanSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBanSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanSach4MouseClicked(evt);
            }
        });

        lbNhaCungCap5.setBackground(new java.awt.Color(0, 204, 204));
        lbNhaCungCap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhaCungCap5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhaCungCap5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Suppliers.png"))); // NOI18N
        lbNhaCungCap5.setText("  Nhà xuất bản");
        lbNhaCungCap5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhaCungCap5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhaCungCap5MouseClicked(evt);
            }
        });

        lbPhieu10.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coupons.png"))); // NOI18N
        lbPhieu10.setText("  Phiếu nhập");
        lbPhieu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu10MouseClicked(evt);
            }
        });

        lbNhapSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhapSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhapSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhapSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImportBook.png"))); // NOI18N
        lbNhapSach4.setText("  Nhập sách");
        lbNhapSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhapSach4.setOpaque(true);
        lbNhapSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhapSach4MouseClicked(evt);
            }
        });

        lbKH11.setBackground(new java.awt.Color(0, 204, 204));
        lbKH11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbKH11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbKH11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        lbKH11.setText("  Khách hàng");
        lbKH11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbKH11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbKH11MouseClicked(evt);
            }
        });

        lblBill4.setBackground(new java.awt.Color(0, 204, 204));
        lblBill4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBill4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill.png"))); // NOI18N
        lblBill4.setText("  Hóa đơn");
        lblBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBill4MouseClicked(evt);
            }
        });

        lbBookStore4.setBackground(new java.awt.Color(0, 204, 204));
        lbBookStore4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBookStore4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBookStore4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookStore.png"))); // NOI18N
        lbBookStore4.setText(" Cửa hàng sách");
        lbBookStore4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBookStore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBookStore4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThanhMenu4Layout = new javax.swing.GroupLayout(ThanhMenu4);
        ThanhMenu4.setLayout(ThanhMenu4Layout);
        ThanhMenu4Layout.setHorizontalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBanSach4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhanVien4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapSach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhaCungCap5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbKH11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBill4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBookStore4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThanhMenu4Layout.setVerticalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhanVien4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhapSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhaCungCap5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbKH11)
                .addGap(18, 18, 18)
                .addComponent(lbPhieu10)
                .addGap(18, 18, 18)
                .addComponent(lblBill4)
                .addGap(18, 18, 18)
                .addComponent(lbBookStore4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TieuDe2.setBackground(new java.awt.Color(153, 102, 0));

        lblThayDoiTK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        lblThayDoiTK3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThayDoiTK3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThayDoiTK3MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Hệ thống quản lý cửa hàng sách");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel18.setText("jLabel3");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TieuDe2Layout = new javax.swing.GroupLayout(TieuDe2);
        TieuDe2.setLayout(TieuDe2Layout);
        TieuDe2Layout.setHorizontalGroup(
            TieuDe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDe2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThayDoiTK3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        TieuDe2Layout.setVerticalGroup(
            TieuDe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThayDoiTK3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(ThanhMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addComponent(BangChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TieuDe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(TieuDe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addComponent(ThanhMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNXBActionPerformed
        // TODO add your handling code here:
        if(cbxNXB.getSelectedIndex()==0){
            txtFind.setEnabled(false);
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(false);
            btnEdit.setEnabled(false);
            btnConfirm.setEnabled(false);
            NXB = (String) cbxNXB.getSelectedItem();
            ShowTableKho();
        }
        else{
            txtFind.setEnabled(true);
            btnAdd.setEnabled(true);
            btnDelete.setEnabled(true);
            btnEdit.setEnabled(true);
            btnConfirm.setEnabled(true);
            NXB = (String) cbxNXB.getSelectedItem();
            ShowTableKho();
        }
    }//GEN-LAST:event_cbxNXBActionPerformed

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
        model_kho.setRowCount(0);
        String find = txtFind.getText();
        
        for(DTOKhoSach s : list){
            if(s.getTenSach()==null){
                continue;
            }
            if(NXB.equals(s.getNhaXuatBan())){
                if(s.getMaSach().contains(find) || s.getTenSach().contains(find) || String.valueOf(s.getNam()).contains(find) || s.getTenTacGia().contains(find) 
                    || s.getNhaXuatBan().contains(find) || String.valueOf(s.getSl()).contains(find) || String.valueOf(s.getGia()).contains(find) || s.getTheLoai().contains(find)){
                        model_kho.addRow(new Object[]{
                            s.getMaSach(), s.getTenSach(), s.getNam(), s.getTenTacGia(), s.getNhaXuatBan(), s.getSl(), s.getGia(),s.getTheLoai()
                });
            }
            }
        }
    }//GEN-LAST:event_txtFindKeyReleased

    public int tinhthanhtien(int sl,int gia){
        return sl*gia;
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String str;
        int sl = 0;
        int thanhtien=0;
        boolean flag = false;
        int selectedrow = tbKho.getSelectedRow();
        if(selectedrow == -1 ){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn sách để nhập!");
            return;
        }
        else{
            for(int i=0;i<tbNhap.getRowCount();i++){
                if(tbKho.getValueAt(selectedrow, 0).equals(tbNhap.getValueAt(i, 0))){
                    JOptionPane.showMessageDialog(rootPane, "Sách đã có trong bảng nhập sách!");
                    return;
                }
            }
            do{
                flag=false;
                str = JOptionPane.showInputDialog("Nhập số lượng");
                System.out.println(str);
                if( str.isEmpty() ){
                    JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số lượng sách!");
                    flag=true;
                }
                else{
                    try{
                        sl = Integer.parseInt(str);
                        if(sl<=0){
                            JOptionPane.showMessageDialog(rootPane, "Số lượng nhập phải lớn hơn 0!");
                            flag=true;
                        }  
                    }
                    catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(rootPane, "Số lượng nhập sai cú pháp!");
                        flag=true;
                    }
                }
            }
            while(flag);  
        }
        for(DTOKhoSach s : list){
            if(s.getMaSach().equals(tbKho.getValueAt(selectedrow, 0))){
                thanhtien = tinhthanhtien(sl, s.getGia());
                tongtien +=thanhtien;
            }
        }
        model_nhap.addRow(new Object[]{
            tbKho.getValueAt(selectedrow, 0),tbKho.getValueAt(selectedrow, 1),sl,tbKho.getValueAt(selectedrow, 6),currencyVN.format(thanhtien)
        });
        lblTongTien.setText(currencyVN.format(tongtien));
        
        if(tbNhap.getRowCount() != 0){
           cbxNXB.setEnabled(false);
        }
      
    }//GEN-LAST:event_btnAddActionPerformed
  
    private void txtFindFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindFocusGained
        // TODO add your handling code here:
        if(txtFind.getText().trim().equals("Nhập thông tin để tìm kiếm")){
            txtFind.setText("");
            txtFind.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtFindFocusGained

    private void txtFindFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindFocusLost
        // TODO add your handling code here:
        if(txtFind.getText().trim().equals("")){
            txtFind.setText("Nhập thông tin để tìm kiếm");
            txtFind.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtFindFocusLost

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int a=0;
        int selectedrow = tbNhap.getSelectedRow();
        if(selectedrow == -1){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn sách trong bảng nhập sách mà bạn muốn xóa!");
            return;
        }
        else{
            for(DTOKhoSach s : list){
                if(s.getMaSach().equals(tbNhap.getValueAt(selectedrow, 0))){
                    a = s.getGia();
                }
            }
            tongtien-= (int)tbNhap.getValueAt(selectedrow, 2) * a;
            lblTongTien.setText(currencyVN.format(tongtien));
            model_nhap.removeRow(selectedrow);
            if(tbNhap.getRowCount() == 0 ){
            cbxNXB.setEnabled(true);
            }
            return;
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String str;
        int a=0;
        int sl=0;
        boolean flag = false;
        int selectedrow = tbNhap.getSelectedRow();
        if(selectedrow == -1){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn sách trong bảng nhập sách mà bạn muốn sửa!");
        }
        else{
            do{
                str = JOptionPane.showInputDialog("Nhập số lượng");
                if(str.isEmpty()){
                    JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số lượng sách!");
                    flag=true;
                }
                else{
                    try{
                        sl = Integer.parseInt(str);
                        if(sl<=0){
                            JOptionPane.showMessageDialog(rootPane, "Số lượng nhập phải lớn hơn 0!");
                            flag=true;
                        }
                    }
                    catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(rootPane, "Số lượng nhập sai cú pháp!");
                        flag=true;
                    }
                }
                        
            }
            while(flag);
        }
        
        for(DTOKhoSach s : list){
                if(s.getMaSach().equals(tbNhap.getValueAt(selectedrow, 0))){
                    a = s.getGia();
                }
            }
        tongtien -= (int)tbNhap.getValueAt(selectedrow, 2) * a;
        model_nhap.setValueAt(sl, selectedrow, 2);
        model_nhap.setValueAt(currencyVN.format(tinhthanhtien(sl, a)), selectedrow, 4);
        tongtien += (int)tbNhap.getValueAt(selectedrow, 2) * a;
        lblTongTien.setText(currencyVN.format(tongtien));
    }//GEN-LAST:event_btnEditActionPerformed

    private void lbNhanVien4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanVien4MouseClicked
        // TODO add your handling code here:
        NhanVien_View a = new NhanVien_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhanVien4MouseClicked

    private void lbBanSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanSach4MouseClicked
        // TODO add your handling code here:
        BanHang_View a = new BanHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBanSach4MouseClicked

    private void lbNhaCungCap5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhaCungCap5MouseClicked
        // TODO add your handling code here:
        NXB_View a = new NXB_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhaCungCap5MouseClicked

    private void lbPhieu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu10MouseClicked
        // TODO add your handling code here:
        PhieuNhap a = new PhieuNhap(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPhieu10MouseClicked

    private void lbNhapSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhapSach4MouseClicked
        // TODO add your handling code here:
        NhapHangView a = new NhapHangView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhapSach4MouseClicked

    private void lbKH11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKH11MouseClicked
        // TODO add your handling code here:
        KhachHang_View a = new KhachHang_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbKH11MouseClicked

    private void lblBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBill4MouseClicked
        // TODO add your handling code here:
        HoaDon_View a = new HoaDon_View(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBill4MouseClicked

    private void lbBookStore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBookStore4MouseClicked
        // TODO add your handling code here:
        KhoSachView a = new KhoSachView(MaNV,TenNV);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBookStore4MouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        txtFind.setEnabled(true);
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(true);
        btnEdit.setEnabled(true);
        cbxNXB.setEnabled(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        int a=0;
        DTOPhieuNhap s = new DTOPhieuNhap();
        String maNXB=null;
        s.setMaPhieu(Integer.parseInt(lblMaPhieu.getText()));
        s.setMaNV(lblMaNV.getText());
        for(DTONhaXuatBan ss : list_NXB){
            if(cbxNXB.getSelectedItem().equals(ss.getTen())){
                maNXB=ss.getMa();
            }
        }
        s.setMaNXB(maNXB);
        try {
            s.setNgayNhap(new SimpleDateFormat("dd/MM/yyyy").parse(lblNgayNhap.getText()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        s.setTongTien(tongtien);

        //Tinh toan cong vao sl sach trong kho:
        for (int i = 0; i < tblPhieuNhap.getRowCount();i++){
            for (DTOKhoSach slTonKho : list){
                if(slTonKho.getMaSach().equals(tblPhieuNhap.getValueAt(i, 0))){
                    System.out.println(tblPhieuNhap.getValueAt(i, 2));
                    if(new DAOKhoSach().CongSLBanHang(slTonKho.getMaSach(), slTonKho.getSl(), (int) tblPhieuNhap.getValueAt(i, 2))){
                        slTonKho.setSl(slTonKho.getSl() + (int) tblPhieuNhap.getValueAt(i, 2));
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(rootPane, new BUSPhieuNhap().addPhieuNhap(s));
        //Them thong tin hang vao bang chi tiet phieu nhap:
        for (int i = 0; i < tblPhieuNhap.getRowCount(); i++){
            DTOChiTietPhieuNhap ctpn =  new DTOChiTietPhieuNhap();
            ctpn.setMaPhieu(Integer.parseInt(lblMaPhieu.getText()));
            ctpn.setMaSach((java.lang.String) tblPhieuNhap.getValueAt(i, 0));
            ctpn.setTenSach((java.lang.String) tblPhieuNhap.getValueAt(i, 1));
            for(DTOKhoSach ss : list){
                if(ss.getMaSach().equals(tblPhieuNhap.getValueAt(i, 0))){
                    a=ss.getGia();
                }
            }
            System.out.println(a);
            ctpn.setGiaSach(a);
            ctpn.setSLNhap((int) tblPhieuNhap.getValueAt(i, 2));
            if(new BUSChiTietPhieuNhap().addChiTietPhieuNhap(ctpn).equals("Xảy ra lỗi")){
                JOptionPane.showMessageDialog(rootPane, "Xảy ra lỗi");
                new BUSChiTietPhieuNhap().deleteChiTietPhieuNhap(s);
                new BUSPhieuNhap().deletePhieuNhap(s);
                return;
            }
        }

        jTabbedPane1.setSelectedIndex(0);
        Reset();

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here

        if(tbNhap.getRowCount() == 0){
            JOptionPane.showMessageDialog(rootPane, "Chưa có sách trong bảng nhập sách!");
            return;
        }
        txtFind.setEnabled(false);
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        cbxNXB.setEnabled(false);
        jTabbedPane1.setSelectedIndex(1);

        Random rd = new Random();
        String code = Integer.toString(new DAOPhieuNhap().getMaxMaPhieuNhap()+ 1);

        LocalDate localDate = LocalDate.now();
        String year = Integer.toString(localDate.getYear());//lay ra nam hien tai
        String day = Integer.toString(localDate.getDayOfMonth());//lay ra ngay hien tai
        String month = Integer.toString(localDate.getMonthValue());
        String date = day+"/"+month+"/"+year;

        lblMaPhieu.setText(code);
        lblNgayNhap.setText(date);
        lblTongHoaDon.setText(lblTongTien.getText());
        tblPhieuNhap.setModel(model_nhap);

        if(tblPhieuNhap.getRowCount()!=0){
            jTabbedPane1.setEnabledAt(1, true);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tbKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoMouseClicked
        // TODO add your handling code here:
        int selectedrow = tbKho.getSelectedRow();
        //        txtFind.setText((String) tbKho.getValueAt(selectedrow, 0));
    }//GEN-LAST:event_tbKhoMouseClicked

    private void lblThayDoiTK3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThayDoiTK3MouseClicked
        // TODO add your handling code here:
        SuaTaiKhoan a = new SuaTaiKhoan(MaNV,TenNV);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        //this.setVisible(true);
    }//GEN-LAST:event_lblThayDoiTK3MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void Reset(){
        cbxNXB.setEnabled(true);
        cbxNXB.setSelectedIndex(0);
        model_kho.setRowCount(0);
        model_nhap.setRowCount(0);
        lblMaNV.setText("");
        lblMaPhieu.setText("");
        lblNgayNhap.setText("");
        lblTenNV.setText("");
        lblTongHoaDon.setText("");
        lblTongTien.setText("");
        lblMaNV.setText(MaNV);
        lblTenNV.setText(TenNV);
        tongtien = 0;
         jTabbedPane1.setEnabledAt(1, false);
    }
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapHangView(MaNV,TenNV).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BangChon;
    private javax.swing.JPanel ThanhMenu4;
    private javax.swing.JPanel TieuDe;
    private javax.swing.JPanel TieuDe2;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cbxNXB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpChiTietHoaDon;
    private javax.swing.JPanel jpThongTinSanPham;
    private javax.swing.JLabel lbBanSach4;
    private javax.swing.JLabel lbBookStore4;
    private javax.swing.JLabel lbKH11;
    private javax.swing.JLabel lbNhaCungCap5;
    private javax.swing.JLabel lbNhanVien4;
    private javax.swing.JLabel lbNhapSach4;
    private javax.swing.JLabel lbPhieu10;
    private javax.swing.JLabel lblBill4;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThayDoiTK2;
    private javax.swing.JLabel lblThayDoiTK3;
    private javax.swing.JLabel lblTongHoaDon;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tbKho;
    private javax.swing.JTable tbNhap;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
