/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAOTaiKhoan;
import Model.TaiKhoan;
import controller.DAONhanVien;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;



/**
 *
 * @author ASUS
 */
public class NhanVien_View extends javax.swing.JFrame {

   DefaultTableModel model;
   DefaultTableModel model1;
    ArrayList<NhanVien> listnv;
    ArrayList<TaiKhoan> listtk;
 
   
    public NhanVien_View() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);//phat toan man hinh
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setPreferredSize(screenSize);
        listnv = new DAONhanVien().getNhanVien();
        listtk= new DAOTaiKhoan().getListTK();
       
        model = (DefaultTableModel) thongtinnv.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Ten Nhan Vien", "Que Quan", "So Ngay Lam", "Cong Viec Chinh"
        });
        model1 = (DefaultTableModel) dstaikhoan.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "Ma Nhan Vien", "Mật Khẩu", "Email", "Trạng Thái"
      });
       themnv.setVisible(false);
       
        showtable();
       showtable1();
    }
    
    public void showtable(){
        for (NhanVien s: listnv){
          
            model.addRow(new Object[]{ 
                    s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
            });
        }
    }
     public void showtable1(){
        for (TaiKhoan s: listtk){
          
            model1.addRow(new Object[]{ 
                    s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BackGround = new javax.swing.JPanel();
        tabledanhsach = new javax.swing.JPanel();
        danhsach = new javax.swing.JTabbedPane();
        bangds = new javax.swing.JPanel();
        scrollthongtin = new javax.swing.JScrollPane();
        thongtinnv = new javax.swing.JTable();
        paneltaikhoan = new javax.swing.JPanel();
        scrollacount = new javax.swing.JScrollPane();
        dstaikhoan = new javax.swing.JTable();
        BangChon = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        boxsearch = new javax.swing.JComboBox<>();
        txthienthi = new javax.swing.JTextField();
        block = new javax.swing.JButton();
        TieuDe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        themnv = new javax.swing.JPanel();
        addten = new javax.swing.JTextField();
        addhometown = new javax.swing.JTextField();
        addma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbt = new javax.swing.JButton();
        cancelbt = new javax.swing.JButton();
        setcongviec = new javax.swing.JComboBox<>();
        ThanhMenu4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbNhanVien4 = new javax.swing.JLabel();
        lbBanSach4 = new javax.swing.JLabel();
        lbNhaCungCap5 = new javax.swing.JLabel();
        lbPhieu10 = new javax.swing.JLabel();
        lbNhapSach4 = new javax.swing.JLabel();
        lbPhieu11 = new javax.swing.JLabel();
        lblBill4 = new javax.swing.JLabel();
        BookStore4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));

        thongtinnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        thongtinnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongtinnvMouseClicked(evt);
            }
        });
        scrollthongtin.setViewportView(thongtinnv);

        javax.swing.GroupLayout bangdsLayout = new javax.swing.GroupLayout(bangds);
        bangds.setLayout(bangdsLayout);
        bangdsLayout.setHorizontalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        bangdsLayout.setVerticalGroup(
            bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(bangdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bangdsLayout.createSequentialGroup()
                    .addComponent(scrollthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        danhsach.addTab("thông tin nhân viên ", bangds);

        dstaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dstaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dstaikhoanMouseClicked(evt);
            }
        });
        scrollacount.setViewportView(dstaikhoan);

        javax.swing.GroupLayout paneltaikhoanLayout = new javax.swing.GroupLayout(paneltaikhoan);
        paneltaikhoan.setLayout(paneltaikhoanLayout);
        paneltaikhoanLayout.setHorizontalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE))
        );
        paneltaikhoanLayout.setVerticalGroup(
            paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(paneltaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollacount, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
        );

        danhsach.addTab("tài khoản", paneltaikhoan);

        javax.swing.GroupLayout tabledanhsachLayout = new javax.swing.GroupLayout(tabledanhsach);
        tabledanhsach.setLayout(tabledanhsachLayout);
        tabledanhsachLayout.setHorizontalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabledanhsachLayout.createSequentialGroup()
                .addComponent(danhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabledanhsachLayout.setVerticalGroup(
            tabledanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabledanhsachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(danhsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BangChon.setBackground(new java.awt.Color(0, 153, 153));

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-friend.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        boxsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tìm kiếm theo tên", "tìm kiếm theo mã nhân viên", "tìm kiếm theo công việc", "tìm kiếm theo quê quán" }));
        boxsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsearchActionPerformed(evt);
            }
        });

        txthienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthienthiActionPerformed(evt);
            }
        });
        txthienthi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthienthiKeyReleased(evt);
            }
        });

        block.setBackground(new java.awt.Color(0, 204, 153));
        block.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        block.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        block.setText("block");
        block.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blockItemStateChanged(evt);
            }
        });
        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BangChonLayout = new javax.swing.GroupLayout(BangChon);
        BangChon.setLayout(BangChonLayout);
        BangChonLayout.setHorizontalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BangChonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txthienthi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        BangChonLayout.setVerticalGroup(
            BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BangChonLayout.createSequentialGroup()
                .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BangChonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BangChonLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxsearch, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txthienthi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BangChonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BangChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(block, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        TieuDe.setBackground(new java.awt.Color(153, 102, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Book Sales Software");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N

        javax.swing.GroupLayout TieuDeLayout = new javax.swing.GroupLayout(TieuDe);
        TieuDe.setLayout(TieuDeLayout);
        TieuDeLayout.setHorizontalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 847, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        TieuDeLayout.setVerticalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TieuDeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))))
        );

        themnv.setBackground(new java.awt.Color(51, 255, 255));
        themnv.setForeground(new java.awt.Color(255, 255, 255));
        themnv.setEnabled(false);
        themnv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                themnvAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        addhometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhometownActionPerformed(evt);
            }
        });

        addma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Nhân Viên");

        jLabel7.setText("Họ Và Tên");

        jLabel8.setText("Quê Quán");

        jLabel10.setText("Công Việc Chính");

        addbt.setBackground(new java.awt.Color(0, 204, 153));
        addbt.setText("Thêm");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        cancelbt.setBackground(new java.awt.Color(0, 204, 153));
        cancelbt.setText("Hủy");
        cancelbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtActionPerformed(evt);
            }
        });

        setcongviec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhan vien kho", "nhan vien ban hang" }));

        javax.swing.GroupLayout themnvLayout = new javax.swing.GroupLayout(themnv);
        themnv.setLayout(themnvLayout);
        themnvLayout.setHorizontalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(themnvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themnvLayout.createSequentialGroup()
                        .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themnvLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(addten)
            .addComponent(addhometown)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addma)
            .addComponent(setcongviec, 0, 558, Short.MAX_VALUE)
        );
        themnvLayout.setVerticalGroup(
            themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themnvLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addten, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setcongviec, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(themnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        ThanhMenu4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon minion.png"))); // NOI18N
        jLabel13.setText("Hi You");

        lbNhanVien4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhanVien4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhanVien4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Employee.png"))); // NOI18N
        lbNhanVien4.setText("  Nhân viên");
        lbNhanVien4.setToolTipText("");
        lbNhanVien4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhanVien4.setOpaque(true);
        lbNhanVien4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanVien4MouseClicked(evt);
            }
        });

        lbBanSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbBanSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbBanSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookSales.png"))); // NOI18N
        lbBanSach4.setText("  Bán sách");
        lbBanSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBanSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanSach4MouseClicked(evt);
            }
        });

        lbNhaCungCap5.setBackground(new java.awt.Color(0, 204, 204));
        lbNhaCungCap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhaCungCap5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhaCungCap5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Suppliers.png"))); // NOI18N
        lbNhaCungCap5.setText("  Nhà xuất bản");
        lbNhaCungCap5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhaCungCap5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhaCungCap5MouseClicked(evt);
            }
        });

        lbPhieu10.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Coupons.png"))); // NOI18N
        lbPhieu10.setText("  Phiếu nhập");
        lbPhieu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu10MouseClicked(evt);
            }
        });

        lbNhapSach4.setBackground(new java.awt.Color(0, 204, 204));
        lbNhapSach4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNhapSach4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhapSach4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImportBook.png"))); // NOI18N
        lbNhapSach4.setText("  Nhập sách");
        lbNhapSach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhapSach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhapSach4MouseClicked(evt);
            }
        });

        lbPhieu11.setBackground(new java.awt.Color(0, 204, 204));
        lbPhieu11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhieu11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPhieu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Customer.png"))); // NOI18N
        lbPhieu11.setText("  Khách hàng");
        lbPhieu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPhieu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPhieu11MouseClicked(evt);
            }
        });

        lblBill4.setBackground(new java.awt.Color(0, 204, 204));
        lblBill4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBill4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill.png"))); // NOI18N
        lblBill4.setText("  Hóa đơn");
        lblBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBill4MouseClicked(evt);
            }
        });

        BookStore4.setBackground(new java.awt.Color(0, 204, 204));
        BookStore4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookStore4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookStore4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BookStore.png"))); // NOI18N
        BookStore4.setText(" Cửa hàng sách");
        BookStore4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookStore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookStore4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ThanhMenu4Layout = new javax.swing.GroupLayout(ThanhMenu4);
        ThanhMenu4.setLayout(ThanhMenu4Layout);
        ThanhMenu4Layout.setHorizontalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBanSach4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhanVien4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhapSach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNhaCungCap5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPhieu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBill4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookStore4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThanhMenu4Layout.setVerticalGroup(
            ThanhMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhMenu4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhanVien4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhapSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNhaCungCap5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPhieu11)
                .addGap(18, 18, 18)
                .addComponent(lbPhieu10)
                .addGap(18, 18, 18)
                .addComponent(lblBill4)
                .addGap(18, 18, 18)
                .addComponent(BookStore4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(ThanhMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabledanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(BangChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackGroundLayout.createSequentialGroup()
                    .addGap(442, 442, 442)
                    .addComponent(themnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabledanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
            .addComponent(ThanhMenu4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackGroundLayout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addComponent(themnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    tabledanhsach.setVisible(false);
      themnv.setVisible(true);

                
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selected =thongtinnv.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần xóa");
        }
       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
    NhanVien nv = null;
    for (NhanVien nhanVien : listnv) {
        if (nhanVien.getMaNV().equals(maNV)) { // Tìm đối tượng NhanVien có mã nhân viên tương ứng trong ArrayList
            nv = nhanVien;
            break;
        }
    }
    if (nv != null) { // Nếu tìm thấy đối tượng NhanVien
       
        if (new DAONhanVien().updateNhanvien(nv)) { // Update dữ liệu trong CSDL SQL
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công.");
             int index = listnv.indexOf(nv); // Tìm vị trí của đối tượng NhanVien trong ArrayList
            listnv.remove(index); // Xóa đối tượng NhanVien khỏi ArrayList
             model.removeRow(index); // Xóa dòng tương ứng trong table 
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa thất bại.");
        }
    } 
}
      
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void boxsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxsearchActionPerformed

    private void blockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blockItemStateChanged
   
         
    }//GEN-LAST:event_blockItemStateChanged

   @SuppressWarnings("StringEquality")
    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
        // TODO add your handling code here:
         int selected =dstaikhoan.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(rootPane, "mời bạn chọn nhân viên cần khóa tài khoản !");
            return;
        }
        
       String maNV = txthienthi.getText(); // Lấy mã nhân viên từ textfield
if (maNV != null && !maNV.trim().equals("")) { // Kiểm tra mã nhân viên có hợp lệ hay không
    TaiKhoan tk = null;
    for (TaiKhoan taikhoan : listtk) {
         if(taikhoan.getTrangThai().equalsIgnoreCase("mo")&&taikhoan.getMaNhanVien().equals(maNV)){
             tk = taikhoan;
             break;
        }
      
    }
    if (tk != null) { // Nếu tìm thấy đối tượng NhanVien
       
        if (new DAOTaiKhoan().updateTaiKhoan(tk)) { // Update dữ liệu trong CSDL SQL
            JOptionPane.showMessageDialog(rootPane, "Khóa thành công");
            showResult();
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Khóa thất bại.");
        }
    } 
}
    
        showResult1();
    }//GEN-LAST:event_blockActionPerformed
 public void showResult1() {
     model1.setRowCount(0);
    listtk = new DAOTaiKhoan().getListTK();
    for(TaiKhoan s :listtk){
        model1.addRow(new Object[]{
           s.getMaNhanVien(), s.getMatKhau(), s.getEmail(), s.getTrangThai()
        });
    }
 }    
    private void addmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmaActionPerformed

    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ trường văn bản
       
       
        themnv.setVisible(false);
       tabledanhsach.setVisible(true);
        NhanVien nv =new NhanVien();
         for (NhanVien nhanVien : listnv) {
            if (nhanVien.getMaNV().equals(addma.getText())) { // Tìm đối tượng NhanVien có mã nhân viên tương ứng trong ArrayList
             JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã trùng mời bạn nhập lại !");
              addma.setText("");
            addten.setText("");
            addhometown.setText("");
            setcongviec.setSelectedIndex(0);
          return;
        }
    }   
         nv.setMaNV(addma.getText());
        nv.setTenNV(addten.getText()); 
        nv.setQueQuan(addhometown.getText()); 
        nv.setCongViec((String) setcongviec.getSelectedItem());
      
         if(new DAONhanVien().addNhanvien(nv)){
              JOptionPane.showMessageDialog(rootPane, "add success");
                listnv.add(nv);
         }else if (null ==nv) {
             JOptionPane.showMessageDialog(rootPane, "Student's ID cannot be duplicated");
         }
         addma.setText("");
         addten.setText("");
         addhometown.setText("");
          setcongviec.setSelectedIndex(0);
         showResult();
         
    }//GEN-LAST:event_addbtActionPerformed
     
    public void showResult() {
    NhanVien s = listnv.get(listnv.size()-1);
        model.addRow(new Object[]{
            s.getMaNV(), s.getTenNV(), s.getQueQuan(), s.getSoNgayLam(), s.getCongViec()
        });
}
    private void themnvAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_themnvAncestorAdded
     
    }//GEN-LAST:event_themnvAncestorAdded

    private void cancelbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtActionPerformed
        // TODO add your handling code here:
        themnv.setVisible(false);
        tabledanhsach.setVisible(true);
        
    }//GEN-LAST:event_cancelbtActionPerformed

    private void thongtinnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongtinnvMouseClicked
                    int selected = thongtinnv.getSelectedRow();
                    
                    txthienthi.setText((String) thongtinnv.getValueAt(selected, 0));
    }//GEN-LAST:event_thongtinnvMouseClicked

    private void addhometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addhometownActionPerformed

    private void txthienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthienthiActionPerformed
       
    }//GEN-LAST:event_txthienthiActionPerformed
 
    private void txthienthiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthienthiKeyReleased
        // TODO add your handling code here:
      
         // TODO add your handling code here:
     String selectedItem = boxsearch.getSelectedItem().toString();
      switch(selectedItem){
     case "tìm kiếm theo tên":
        
               model.setRowCount(0);
      for (NhanVien nv : listnv) {
    if (nv.getTenNV().contains(txthienthi.getText())) {
                Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(),nv.getCongViec()};
                model.addRow(rowData);
            }
        }
        thongtinnv.setModel(model);
        break;
         
         
     case "tìm kiếm theo quê quán":
               model.setRowCount(0);
                for (NhanVien nv : listnv) {
              if (nv.getQueQuan().contains(txthienthi.getText())) {
                          Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(),nv.getCongViec()};
                          model.addRow(rowData);
                      }
                  }
                  thongtinnv.setModel(model);
        break;
     case "tìm kiếm theo công việc":
          model.setRowCount(0);
                for (NhanVien nv : listnv) {
              if (nv.getCongViec().contains(txthienthi.getText())) {
                          Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(),nv.getCongViec()};
                          model.addRow(rowData);
                      }
                  }
                  thongtinnv.setModel(model);
          
        break;
     case "tìm kiếm theo mã nhân viên":
        
      
                DefaultTableModel model = (DefaultTableModel) thongtinnv.getModel();
                model.setRowCount(0);
                for (NhanVien nv : listnv) {
                    if (nv.getMaNV().contains(txthienthi.getText())) {
                        Object[] rowData = {nv.getMaNV(), nv.getTenNV(), nv.getQueQuan(), nv.getSoNgayLam(), nv.getCongViec()};
                        model.addRow(rowData);
                    }
                }
                thongtinnv.setModel(model);
                break;
            }
      

    }//GEN-LAST:event_txthienthiKeyReleased

    private void dstaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstaikhoanMouseClicked
        // TODO add your handling code here:
        int selected = dstaikhoan.getSelectedRow();
        
       txthienthi.setText((String) dstaikhoan.getValueAt(selected, 0));
    }//GEN-LAST:event_dstaikhoanMouseClicked

    private void lbNhanVien4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanVien4MouseClicked
        // TODO add your handling code here:
        NhanVien_View a = new NhanVien_View();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhanVien4MouseClicked

    private void lbBanSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanSach4MouseClicked
        // TODO add your handling code here:
        BanHang_View a = new BanHang_View();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBanSach4MouseClicked

    private void lbNhaCungCap5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhaCungCap5MouseClicked
        // TODO add your handling code here:
        NXB_View a = new NXB_View();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhaCungCap5MouseClicked

    private void lbPhieu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu10MouseClicked
        // TODO add your handling code here:
        PhieuNhap a = new PhieuNhap();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lbPhieu10MouseClicked

    private void lbNhapSach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhapSach4MouseClicked
        // TODO add your handling code here:
        NhapHangView a = new NhapHangView();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbNhapSach4MouseClicked

    private void lbPhieu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPhieu11MouseClicked
        // TODO add your handling code here:
        KhachHang_View a = new KhachHang_View();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPhieu11MouseClicked

    private void lblBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBill4MouseClicked
        // TODO add your handling code here:
        HoaDon_View a = new HoaDon_View();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBill4MouseClicked

    private void BookStore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookStore4MouseClicked
        // TODO add your handling code here:
        KhoSachView a = new KhoSachView();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookStore4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NhanVien_View().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BangChon;
    private javax.swing.JLabel BookStore4;
    private javax.swing.JPanel ThanhMenu4;
    private javax.swing.JPanel TieuDe;
    private javax.swing.JButton addbt;
    private javax.swing.JTextField addhometown;
    private javax.swing.JTextField addma;
    private javax.swing.JTextField addten;
    private javax.swing.JPanel bangds;
    private javax.swing.JButton block;
    private javax.swing.JComboBox<String> boxsearch;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton cancelbt;
    private javax.swing.JTabbedPane danhsach;
    private javax.swing.JTable dstaikhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbBanSach4;
    private javax.swing.JLabel lbNhaCungCap5;
    private javax.swing.JLabel lbNhanVien4;
    private javax.swing.JLabel lbNhapSach4;
    private javax.swing.JLabel lbPhieu10;
    private javax.swing.JLabel lbPhieu11;
    private javax.swing.JLabel lblBill4;
    private javax.swing.JPanel paneltaikhoan;
    private javax.swing.JScrollPane scrollacount;
    private javax.swing.JScrollPane scrollthongtin;
    private javax.swing.JComboBox<String> setcongviec;
    private javax.swing.JPanel tabledanhsach;
    public javax.swing.JPanel themnv;
    private javax.swing.JTable thongtinnv;
    private javax.swing.JTextField txthienthi;
    // End of variables declaration//GEN-END:variables

  
}
